updates

diff --git a/trunk/grimoire/init-scripts.d/init.d/etc-rootfs b/trunk/grimoire/init-scripts.d/init.d/etc-rootfs
--- a/trunk/grimoire/init-scripts.d/init.d/etc-rootfs
+++ b/trunk/grimoire/init-scripts.d/init.d/etc-rootfs
@@ -8,7 +8,7 @@
 
 . /lib/lsb/init-functions
 
-if ! rootfs || ! [ -d /etc/rootfs ]; then trap - EXIT; exit 0; fi
+if ! rootfs; then trap - EXIT; exit 0; fi
 
 only start
 deny control
@@ -16,12 +16,23 @@ config
 
 start(){
  copy(){
-  find /etc/rootfs/ -mindepth 1 -maxdepth 1 |
-  xargs -r --max-lines=64 cp -at /etc/
+  if   [ -f /etc/rootname ]; then cp /etc/rootname /etc/origin
+  elif [ -f /etc/hostname ]; then cp /etc/hostname /etc/origin
+  fi
+
+  [ -d       /etc/rootfs/ ] &&
+  /bin/find  /etc/rootfs/ -mindepth 1 -maxdepth 1 |
+  /bin/xargs -r -d '\n' -L64 /bin/cp -at /etc/ --
+
+  /bin/find  /etc/        -mindepth 1 -maxdepth 1 -type f -name \*.rootfs |
+  /bin/sed   's:\(.*\)\.rootfs$:\1.rootfs\n\1:' |
+  /bin/xargs -r -d '\n' -L2 /bin/cp -a --
+
+  return 0
  }
 
- if   log_warning_msg "/etc/rootfs/* to /etc/ copying"; copy
- then log_success_msg "/etc/rootfs/* to /etc/ copied"
- else log_failure_msg "/etc/rootfs/* to /etc/ copy failed"
+ if   log_warning_msg "/etc/rootfs/ to /etc/ copying"; copy
+ then log_success_msg "/etc/rootfs/ to /etc/ copied"
+ else log_failure_msg "/etc/rootfs/ to /etc/ copy failed"; return 1
  fi
 }
