updates

diff --git a/trunk/grimoire/init-scripts.d/init.d/final_check b/trunk/grimoire/init-scripts.d/init.d/final_check
--- a/trunk/grimoire/init-scripts.d/init.d/final_check
+++ b/trunk/grimoire/init-scripts.d/init.d/final_check
@@ -16,7 +16,9 @@
 
 . /lib/lsb/init-functions
 
-if ! rootfs; then trap - EXIT; exit 0; fi
+# do not execute on rootfs
+# only execute on root file systems.
+if rootfs; then trap - EXIT; exit 0; fi
 
 only start
 deny control
@@ -48,9 +50,12 @@ start(){
    echo "/etc/init.d/$1 reported an error"
    echo "reboot/shutdown request denied"
    echo "Rebounded to runlevel 3"
+   echo "This message originates from /etc/issue"
+   echo "Please edit the file and remove the error message"
+   echo "after the error condition is fixed"
   }
 
-  deny(){ warn $1 | tee -a /etc/issue.rootfs; alert; REPLY=3; rebound; }
+  deny(){ warn $1 | tee -a /etc/issue; alert; REPLY=3; rebound; }
 
     if [ -f /var/log/init/failed/extlinux/stop  ]; then deny extlinux
   elif [ -f /var/log/init/failed/initramfs/stop ]; then deny initramfs
diff --git a/trunk/grimoire/initramfs.d/init.d/initramfs-kernel b/trunk/grimoire/initramfs.d/init.d/initramfs-kernel
--- a/trunk/grimoire/initramfs.d/init.d/initramfs-kernel
+++ b/trunk/grimoire/initramfs.d/init.d/initramfs-kernel
@@ -10,12 +10,14 @@
 # Copyright 2013 by Kyle Sallee, all rights reserved.
 # for use with Modern Magic only
 
-if ! [ -d /boot/linux/ ]; then
- if   /bin/find /usr/share/linux/ -type f -name kernel | /bin/grep -q .
- then /bin/mkdir -m 700 /boot/linux/
- else exit 0
- fi
-fi
+[ -d /boot/ ] || exit 0
+
+# if ! [ -d /boot/linux/ ]; then
+#  if   /bin/find /usr/share/linux/ -type f -name kernel | /bin/grep -q .
+#  then /bin/mkdir -m 700 /boot/linux/
+#  else exit 0
+#  fi
+# fi
 
 . /lib/lsb/init-functions
 
@@ -66,14 +68,23 @@ current(){
 run(){
  if   log_warning_msg "update"; update
  then log_success_msg "update"
- else log_failure_msg "update"; return 1
+ else log_failure_msg "update"; status; return 1
+ fi
+}
+
+alsoav(){
+ if [ -z "$AV" ]; then
+  log_failure_msg ": When /boot/ exists "
+  log_failure_msg ": linux-kernel must also be installed."
+  log_failure_msg ": /boot/ is required only when"
+  log_failure_msg ": $HOSTNAME is the progenitor for rootfs."
  fi
 }
 
 status(){
  if   log_warning_msg "check"; current
  then log_success_msg "check status:     current"
- else log_warning_msg "check status: not current"; return 1
+ else log_warning_msg "check status: not current"; alsoav; return 1
  fi
 }
 
