Updates

diff --git a/trunk/grimoire/install.d/init.d.on/find_ir b/trunk/grimoire/install.d/init.d.on/find_ir
--- a/trunk/grimoire/install.d/init.d.on/find_ir
+++ b/trunk/grimoire/install.d/init.d.on/find_ir
@@ -50,29 +50,27 @@ start(){
   echo "Install/Rescue Image not found."
   echo "Discover the block device for"
   echo "the Install/Rescue Image and"
-  echo "make that the root device"
+  echo "make that device mount point /media/IR"
   echo "by editing /etc/fstab"
   echo "Sorry for the inconvenience."
   echo "Press enter when prompted for password."
   echo "When complete type exit to resume"
-  sulogin -t 300 /dev/console  &>/dev/console  0</dev/console
+  sulogin -t 300 /dev/console &>/dev/console 0</dev/console
  }
 
- set_root(){
-  sed  -i 's:\t: :g; \, / ,d'            /etc/fstab
-  echo    "$1 / auto defaults,ro 0 0" >> /etc/fstab
+ set_IR(){
+  echo "$1 /media/IR auto defaults,ro 0 0" >> /etc/fstab
  }
 
- on_ir(){ grep -q boot=IR /proc/cmdline; }
+ grep -q boot=IR /proc/cmdline || return
 
- if ! on_ir; then return; fi
-
- log_warning_msg "Sorcerer Install/Rescue Image finding"
-
- if              IRDEV=$( search )
- then set_root "$IRDEV";     log_success_msg "Install/Rescue CD found"
- else manual &>/dev/console; log_failure_msg "Install/Rescue CD not found"
+                             log_warning_msg "Install/Rescue finding"
+ if            IRDEV=$( search )
+ then set_IR "$IRDEV";       log_success_msg "Install/Rescue found"
+ else manual &>/dev/console; log_failure_msg "Install/Rescue not found"
  fi
+ mkdir -p /media/IR
+ mount    /media/IR
 }
 
 
