Updates

diff --git a/trunk/grimoire/busybox b/trunk/grimoire/busybox
--- a/trunk/grimoire/busybox
+++ b/trunk/grimoire/busybox
@@ -76,27 +76,19 @@ build()  {
     cd  ..
 }
 
-linux_avail() {
-  if  !  [  -d  /usr/src/linux/include  ];  then
-    echo  "uClibc used by busybox for static linking"
-    echo  "will fail compilation unless a linux src"
-    echo  "is available at /usr/src/linux"
-    false
-  fi
-}
-
-on_iso()  {
-  if  !  [  -d  /isolinux  ];  then
-    echo  "Please install busybox only on intended Install Rescue images."
-    false
-  fi
-}
+  linux_avail() {
+    if  !  [  -d  /usr/src/linux/include  ];  then
+      echo  "uClibc used by busybox for static linking"
+      echo  "will fail compilation unless a linux src"
+      echo  "is available at /usr/src/linux"
+      false
+    fi
+  }
 
   case  $VERSION  in
     1.3.1)  patch  -p1  <  $SOURCE_CACHE/busybox/1.3.1/${SOURCE[2]##*/}  ;;
   esac
   
-#  on_iso                &&
   linux_avail           &&
   local_install_uClibc  &&
   uClibc_okay=1
@@ -111,30 +103,17 @@ on_iso()  {
          *)  export  CFLAGS="$uClibc -Os -march=i586"  ;;
   esac
 
-  [  "$uClibc_okay"  == "1"  ]      &&
-  yes   ""  |  make  oldconfig      &&
-  make  "CFLAGS=$CFLAGS"            \
-        KBUILD_VERBOSE=1            &&
-  prepare_install                   &&
+  [  "$uClibc_okay"  == "1"  ]  &&
+  yes   ""  |  make  oldconfig  &&
+  make  "CFLAGS=$CFLAGS"        \
+        KBUILD_VERBOSE=1        &&
+  prepare_install               &&
   install  -m 0755  busybox  /bin
-#  &&
-#  mkdir    -p                /bbin  &&
-#  cd                         /bbin  &&
-#  busybox  --help |
-#  grep "^	" |
-#  grep ","        |
-#  tr   -d ' \t'   |
-#  tr   ',' '\n'   |
-#  grep '.'        |
-#  while  read;  do
-#    rm  -f           "$REPLY"
-#    ln  /bin/busybox "$REPLY"
-#  done
 }
 
 
-current()  {
-  if  !  [  -d  /isolinux  ]
-  then  echo  busybox  |  pipe_queue  "$DISPEL_QUEUE"
-  fi
-}
+# current()  {
+#   if  !  [  -d  /isolinux  ]
+#   then  echo  busybox  |  pipe_queue  "$DISPEL_QUEUE"
+#   fi
+# }
