Updates

diff --git a/trunk/grimoire/glibc b/trunk/grimoire/glibc
--- a/trunk/grimoire/glibc
+++ b/trunk/grimoire/glibc
@@ -25,7 +25,7 @@
     stable 2.11.2 2.11.1 2.11 2.10.1
 # unstable 2.12.1
   category development
- attribute library solo
+ attribute library makej solo
    require perl linux-headers
       opts --without-selinux
   optional prelink '' '' for faster loading ELFs
@@ -68,12 +68,14 @@ build(){ (
 
 
  quick_test(){
-  echo "Performing a quick test to see if the new glibc works."
-  if   LD_LIBRARY_PATH="$LLP" $LD_SO /bin/true
-  then echo "glibc is ready to install."
-  else echo "glibc is not working as expected."
-       echo "Compilation aborted before installing new glibc."
-       false
+  if ! [[ $CC =~ -m32 ]]; then
+   echo "Performing a quick test to see if the new glibc works."
+   if   LD_LIBRARY_PATH="$LLP" $LD_SO /bin/true
+   then echo "glibc is ready to install."
+   else echo "glibc is not working as expected."
+        echo "Compilation aborted before installing new glibc."
+        false
+   fi
   fi
  }
 
@@ -84,12 +86,19 @@ build(){ (
  }
 
 
- unset  LTDL_LIBRARY_PATH LD_LIBRARY_PATH LD_RUN_PATH
+ if [[ $HOSTTYPE == x86_64 ]] && [[ $CFLAGS =~ -m32 ]]; then
+  export CC="gcc -m32"
+  opts --host=${MACHTYPE/x86_64/i686}
+ fi
 
- export   CFLAGS="-O2 $( echo "${CFLAGS// /$LF}" | grep march )"
- export CXXFLAGS="$CFLAGS"
- export LDFLAGS='-Wl,-s -Wl,-O1'
- export LC_ALL=C
+ unset LTDL_LIBRARY_PATH LD_LIBRARY_PATH LD_RUN_PATH
+
+    CFLAGS="-O2 $( echo "${CFLAGS// /$LF}" | grep march )"
+  CXXFLAGS="$CFLAGS"
+   LDFLAGS='-Wl,-s -Wl,-O1'
+    LC_ALL=C
+
+ export CFLAGS CXXFLAGS LDFLAGS LC_ALL
 
  mkdir -p $DESTDIR/etc
  touch    $DESTDIR/etc/ld.so.conf
