Updates and fixes

diff --git a/trunk/grimoire/glibc b/trunk/grimoire/glibc
--- a/trunk/grimoire/glibc
+++ b/trunk/grimoire/glibc
@@ -166,12 +166,14 @@ make        include/linux/version.h
 make        include/asm
 cp     -rL  include/{asm,asm-generic,linux}     $IR/usr/include
 cd     ..
-rm     -fr  linux-$LVERSION
+rm     -fr     /usr/include/{asm,asm-generic,linux}  linux-$LVERSION
+cp     -a   $IR/usr/include/*                        /usr/include
 
-if    !  [  -f     /usr/include/linux/version.h  ]
-then  cp    -a  $IR/usr/include/*  /usr/include
-      echo  "Installed missing kernel headers to avoid glibc compile error."
-fi
+### Decided to force installation of linux headers.
+# if    !  [  -f     /usr/include/linux/version.h  ]
+# then  cp    -a  $IR/usr/include/*  /usr/include
+#       echo  "Installed missing kernel headers to avoid glibc compile error."
+# fi
 
 
 HEADERS="--with-headers=$BUILD_DIR/install/usr/include"
