bug fixes

diff --git a/trunk/grimoire/NVIDIA-Linux-x86 b/trunk/grimoire/NVIDIA-Linux-x86
--- a/trunk/grimoire/NVIDIA-Linux-x86
+++ b/trunk/grimoire/NVIDIA-Linux-x86
@@ -42,29 +42,31 @@ Included is a sample config file that works with 2 monitors.
 
 build(){
  fix_install(){
-  mv       $DESTDIR/usr/include     $DESTDIR/usr/nv
+  mv       $DESTDIR/usr/include        $DESTDIR/usr/nvidia
   mkdir -p $DESTDIR/usr/include
-  mv       $DESTDIR/usr/nv/vdpau    $DESTDIR/usr/include
-  mv       $DESTDIR/usr/nv          $DESTDIR/usr/include
+  mv       $DESTDIR/usr/nvidia/vdpau   $DESTDIR/usr/include
+  mv       $DESTDIR/usr/nvidia         $DESTDIR/usr/include
   mkdir -p $DESTDIR/etc/opengl/
 
   if   [ -h $DESTDIR/usr/lib64/libGL.so.1 ]; then
-   mkdir -p $DESTDIR/usr/lib64/nv
-   mv       $DESTDIR/usr/lib64/libGL.* $DESTDIR/usr/lib/nvidia/
+   mkdir -p                            $DESTDIR/usr/lib64/nvidia
+   mv       $DESTDIR/usr/lib64/libGL.* $DESTDIR/usr/lib64/nvidia/
    echo        /usr/lib64/nvidia  >    $DESTDIR/etc/opengl/nvidia
    echo          /usr/lib/nvidia >>    $DESTDIR/etc/opengl/nvidia
    echo /opt/ia32/usr/lib/nvidia >>    $DESTDIR/etc/opengl/nvidia
-   mv       $DESTDIR/usr/lib/*         $DESTDIR/usr/lib64/
-   rmdir    $DESTDIR/usr/lib
+#  mv       $DESTDIR/usr/lib/*         $DESTDIR/usr/lib64/
+#  rmdir    $DESTDIR/usr/lib
   elif [ -h $DESTDIR/usr/lib/libGL.so.1 ]; then
-   mkdir -p $DESTDIR/usr/lib/nv
+   mkdir -p                            $DESTDIR/usr/lib/nvidia
    mv       $DESTDIR/usr/lib/libGL.*   $DESTDIR/usr/lib/nvidia/
    echo          /usr/lib/nvidia  >    $DESTDIR/etc/opengl/nvidia
   fi
 
-  rm -f $DESTDIR/usr/lib/xorg/modules/libwfb.*
-# rm -f $DESTDIR/usr/lib/xorg/modules/extensions/libglx.*
+# NVIDIA's wfb library can not be used by xorg and must not be installed
+  rm -f $DESTDIR/usr/lib{,64}/xorg/modules/*wfb*
+
 ## libglx extension should be installed over xorg-server's libglx
+# rm -f $DESTDIR/usr/lib{,64}/xorg/modules/extensions/libglx.*
 
   return 0
  }
@@ -109,18 +111,25 @@ fi
 --no-cc-version-check
 --no-distro-scripts"
 
-if ! [ -d /usr/src/linux ]; then
- echo    "/usr/src/linux is missing."
- echo    "Therefore, trying to compile and install without kernel module."
- PARAMETERS+=" --no-kernel-module"
-fi
-
 local     BUILD_DIR="$SOURCE_DIR/$SPELL/$SPELL-$VERSION"
 mkdir -p $BUILD_DIR
 cd       $BUILD_DIR
 echo -e "#!/bin/bash\n/sbin/lsmod | grep -v \"nvidia\|rivafb\|nvidiafb\"" > $BUILD_DIR/lsmod
 chmod a+x $BUILD_DIR/lsmod
 export PATH=$BUILD_DIR:$PATH
+
+if   ! [ "$( uname -m )" == "$HOSTNAME" ]; then
+ echo "Assuming compiling on x86_64 architecture while chrooted into"
+ echo "/opt/ia32 onto a Sorcerer IA32 installation."
+ echo    "Therefore, trying to compile and install without kernel module."
+ PARAMETERS+=" --no-kernel-module"
+ echo -e "exec /usr/bin/uname \"\$@\" | sed \"s:x86_64:i686:\"" > $BUILD_DIR/uname
+ chmod a+x $BUILD_DIR/uname
+elif ! [ -d /usr/src/linux ]; then
+ echo    "/usr/src/linux is missing."
+ echo    "Therefore, trying to compile and install without kernel module."
+ PARAMETERS+=" --no-kernel-module"
+fi
 
 mkdir -p $DESTDIR/lib/modules/$LVER/kernel/drivers/video
 mkdir -p $DESTDIR/usr/{include,lib}
