updates and bug fixes

diff --git a/trunk/grimoire/NVIDIA-Linux-x86_64 b/trunk/grimoire/NVIDIA-Linux-x86_64
--- a/trunk/grimoire/NVIDIA-Linux-x86_64
+++ b/trunk/grimoire/NVIDIA-Linux-x86_64
@@ -2,10 +2,11 @@
 # http://www.nvidia.com/Download/index.aspx?lang=en-us
 # It sometimes points to newer drivers.
 
-with version stable 310.32 310.19 304.60
+with version stable 310.44 310.40 310.32 310.19 304.60
+with version 319    319.12
 with version 314    314.14 314.07
 with version 313    313.96 313.18 313.09
-with version 310    310.32 310.19 310.14
+with version 310    310.44 310.40 310.32 310.19 310.14
 with version 304    304.64 304.60 304.43
 with version 295    295.75
 with version 290    290.10
@@ -13,10 +14,11 @@ with version 285    285.05.09 285.03
 with version 280    280.13
 with version 275    275.43 275.36 275.28 275.21
 with version 270    270.41.19 270.41.06
-with base    MesaLib gtk+ libXvMC linux-src xorg-server
+with base    MesaLib gtk+ libXvMC linux-source xorg-server
 with role    kernel
 with trait   library linux-module multilib-fail optimize x86_64 solo x11
 with source  http://us.download.nvidia.com/XFree86/Linux-x86_64/$VERSION/NVIDIA-Linux-x86_64-$VERSION-no-compat32.run
+#with source  http://us.download.nvidia.com/XFree86/Linux-x86_64/$VERSION/NVIDIA-Linux-x86_64-$VERSION.run
 with info    last 20130131
 with info    home http://www.nvidia.com
 with info    vurl http://www.nvidia.com/object/unix.html
@@ -35,39 +37,66 @@ fi
 
 build(){
  fix_install(){
-  mv             $DESTDIR/usr/include        $DESTDIR/usr/nvidia
-  mkdir -pvm 755 $DESTDIR/usr/include
-  mv             $DESTDIR/usr/nvidia/vdpau   $DESTDIR/usr/include
-  mv             $DESTDIR/usr/nvidia         $DESTDIR/usr/include
-  mkdir -pvm 755 $DESTDIR/etc/opengl/
+  mv             "$DESTDIR"/usr/include        "$DESTDIR"/usr/nvidia
+  mkdir -pvm 755 "$DESTDIR"/usr/include/
+  mv             "$DESTDIR"/usr/nvidia/vdpau   "$DESTDIR"/usr/include/
+  mv             "$DESTDIR"/usr/nvidia         "$DESTDIR"/usr/include/
+  mkdir -pvm 755 "$DESTDIR"/etc/opengl/
 
-  if [ -h  $DESTDIR/usr/lib64/libGL.so.1 ]; then
-   mkdir -vpm 755                        $DESTDIR/usr/lib64/nvidia
-   mv    -v   $DESTDIR/usr/lib64/libGL.* $DESTDIR/usr/lib64/nvidia/
-   echo       /usr/lib64/nvidia  >       $DESTDIR/etc/opengl/nvidia
-   echo       /usr/lib/nvidia   >>       $DESTDIR/etc/opengl/nvidia
+  if [ -h  "$DESTDIR"/usr/lib64/libGL.so.1 ]; then
+   mkdir -vpm 755                              "$DESTDIR"/usr/lib64/nvidia/
+   mv    -v   "$DESTDIR"/usr/lib64/libGL.*     "$DESTDIR"/usr/lib64/nvidia/
+   echo       /usr/lib64/nvidia  >             "$DESTDIR"/etc/opengl/nvidia
+   echo       /usr/lib/nvidia   >>             "$DESTDIR"/etc/opengl/nvidia
   fi
 
 # NVIDIA's wfb library can not be used by xorg and must not be installed
-  rm -f $DESTDIR/usr/lib64/xorg/modules/*wfb*
+  rm -f "$DESTDIR"/usr/lib64/xorg/modules/*wfb*
 
 ## libglx extension should be installed over xorg-server's libglx
-# rm -f $DESTDIR/usr/lib64/xorg/modules/extensions/libglx.*
+# rm -f "$DESTDIR"/usr/lib64/xorg/modules/extensions/libglx.*
 
   return 0
  }
 
- MOD_PATH=/usr/lib64/xorg/modules
- PRO="$( get_provider linux-kernel )"
- if   spell_installed $PRO
- then LVER="$( installed_version $PRO  )"
- else LVER="$( available_version linux )"
- fi
+ lversion(){
+  local m=/usr/src/linux/Makefile
 
- case $LVER in
-  3.3) LVER=3.3.0 ;;
-  3.2) LVER=3.2.0 ;;
- esac
+  if   ! [ -f $m ]
+  then return
+  fi
+
+  local v="s:^VERSION=::p;d"
+  local p="s:^PATCHLEVEL=::p;d"
+  local s="s:^SUBLEVEL=::p;d"
+  local e="s:^EXTRAVERSION=::p;d"
+  local c="s: ::g;"
+
+  v=$( sed "$c $v" $m )
+  p=$( sed "$c $p" $m )
+  s=$( sed "$c $s" $m )
+  e=$( sed "$c $e" $m )
+
+  [ -n "$p" ] && v+=".$p"
+  [ -n "$s" ] && v+=".$s"
+  [ -n "$e" ] && v+=".$e"
+
+  LVER="$v"
+ }
+
+ lversion
+ MOD_PATH=/usr/lib64/xorg/modules
+
+ local     BUILD_DIR="$SOURCE_DIR/$SPELL/$SPELL-$VERSION"
+ rm   -fr $BUILD_DIR
+ mkdir -p $BUILD_DIR
+ cd       $BUILD_DIR
+ echo -e "#!/bin/bash\n/sbin/lsmod | grep -v \"nvidia\|rivafb\|nvidiafb\"" > $BUILD_DIR/lsmod
+ chmod a+x $BUILD_DIR/lsmod
+ export PATH=$BUILD_DIR:$PATH
+
+ mkdir -pvm 755 "$DESTDIR/lib/modules/$LVER/kernel/drivers/video"
+ mkdir -pvm 755 "$DESTDIR/usr/{include,lib64}"
 
  PARAMETERS="
 --accept-license
@@ -80,9 +109,9 @@ build(){
 --installer-prefix=$DESTDIR/usr
 --utility-prefix=$DESTDIR/usr
 --documentation-prefix=$DESTDIR/usr
---kernel-source-path=/usr/src/linux
---kernel-install-path=$DESTDIR/lib/modules/$LVER/kernel/drivers/video
 --kernel-name=$LVER
+--kernel-source-path=$PWD/linux
+--kernel-install-path=$DESTDIR/lib/modules/$LVER/kernel/drivers/video
 --no-runlevel-check
 --no-abi-note
 --no-rpms
@@ -93,24 +122,34 @@ build(){
 --no-cc-version-check
 --no-distro-scripts"
 
-if ! [ -d /usr/src/linux ]; then
- echo    "/usr/src/linux is missing."
- echo    "Therefore, trying to compile and install without kernel module."
- PARAMETERS+=" --no-kernel-module"
-fi
+ if ! [ -f /usr/src/linux/Makefile ]; then
+  echo    "/usr/src/linux is missing."
+  echo    "Therefore, trying to compile and install without kernel module."
+  PARAMETERS+=" --no-kernel-module"
+ else
+  local    d=/usr/src/linux
+  local c=$d/.config.custom
+  local s=$d/.config.stock
 
-local     BUILD_DIR="$SOURCE_DIR/$SPELL/$SPELL-$VERSION"
-rm   -fr $BUILD_DIR
-mkdir -p $BUILD_DIR
-cd       $BUILD_DIR
-echo -e "#!/bin/bash\n/sbin/lsmod | grep -v \"nvidia\|rivafb\|nvidiafb\"" > $BUILD_DIR/lsmod
-chmod a+x $BUILD_DIR/lsmod
-export PATH=$BUILD_DIR:$PATH
+  cp -a /usr/src/linux .
 
-mkdir -pvm 755 $DESTDIR/lib/modules/$LVER/kernel/drivers/video
-mkdir -pvm 755 $DESTDIR/usr/{include,lib64}
+    if [ -f $c ]; then cp $c linux/.config
+  elif [ -f $s ]; then cp $s linux/.config
+  else
+   echo "$c does not exist"
+   echo "$s does not exist"
+   echo "$c or $s must exist"
+   echo "try casting linux-config first"
+   return 1
+  fi
+  cd linux
+  yes '' |
+  make oldconfig
+# make silentoldconfig
+  make prepare scripts
+  cd ..
+ fi
 
-yes Yes | sh "${SOURCE[0]}" $PARAMETERS &&
-
-fix_install
+ yes Yes | sh "${SOURCE[0]}" $PARAMETERS &&
+ fix_install
 }
diff --git a/trunk/grimoire/init-scripts.d/init.d/clean_tmp b/trunk/grimoire/init-scripts.d/init.d/clean_tmp
--- a/trunk/grimoire/init-scripts.d/init.d/clean_tmp
+++ b/trunk/grimoire/init-scripts.d/init.d/clean_tmp
@@ -4,8 +4,10 @@
 # Default-Mode: 500
 # Required-Start: $local_fs
 # Default-Start: 1 2 3 4 5
-# Short-Description: removes /fastboot and /forcefsck /tmp/* /var/cache/sorcery/* /aux/reuse
+# Short-Description: removes /aux/run/{pipe,save,source,tmp}/* /tmp/*
 ### END INIT INFO
+
+(( UID == 0 )) || exit 0
 
 . /lib/lsb/init-functions
 
@@ -14,25 +16,19 @@ deny control
 
 start(){
  run(){
-  renew(){
-   if   [ -d $1 ]
-   then find $1 -mindepth 1 -maxdepth 1 |
-        xargs -r --max-lines=64 rm -fr
-        chmod $2 $1
-   else mkdir -pm $2 $1
-   fi
-  } 
-  if   [ -f /fastboot  ]; then rm -f /fastboot;  touch /init; fi
-  if   [ -f /forcefsck ]; then rm -f /forcefsck; touch /init; fi
-  if   [ -d /aux/use   ]; then rm -fr /aux/use; fi
-  renew /tmp 1777
-  if   [ -d /var/cache/sorcery ]
-  then find /var/cache/sorcery -mindepth 1 -maxdepth 1 -type d | sed '\,/ccache,d'| xargs -r --max-lines=64 rm -fr
+  rm   -fr /aux/run/{pipe,save,source,tmp}/*
+  if    ! [       -d      /tmp/ ]
+  then /bin/rm    -f      /tmp/
+       /bin/mkdir -m 1777 /tmp/
+  else /bin/find          /tmp/ -mindepth 1 -maxdepth 1 -print0 |
+       /bin/xargs -r -0   --max-lines=64 \
+       /bin/rm -fr
   fi
+  # Correct ownership and mode for /tmp set by /etc/init.d/var_tmp
  }
 
- if   log_warning_msg "$NAME running"; run
- then log_success_msg "$NAME ran"
- else log_failure_msg "$NAME errored"
+ if   log_warning_msg "/tmp/ cleaning"; run
+ then log_success_msg "/tmp/ cleaned"
+ else log_failure_msg "/tmp/ cleaning failed"
  fi
 }
diff --git a/trunk/grimoire/init-scripts.d/init.d/final_check b/trunk/grimoire/init-scripts.d/init.d/final_check
--- a/trunk/grimoire/init-scripts.d/init.d/final_check
+++ b/trunk/grimoire/init-scripts.d/init.d/final_check
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Copyright 2011 by Kyle Sallee
+# Copyright 2011,2012,2013 by Kyle Sallee
 # All Rights Reserved
 # For use on Sorcerer only
 
@@ -14,6 +14,8 @@
 # and add function declarations:
 # rebound(){ :; }
 
+[ ramfs == "$( /bin/stat -f -c %T / )" ] || exit 0
+
 . /lib/lsb/init-functions
 
 only start
@@ -21,43 +23,42 @@ deny control
 
 start(){
 
-rebound(){
- [ -f /proc/mounts ] || return
- find /var/log/init/ -mindepth 1 -maxdepth 1 |
- while read; do mv $REPLY{,.old}; done
- /etc/init.d/rcS
- telinit $REPLY
- exit
-}
+ rebound(){
+  [ -f /proc/mounts ] || return
+  /bin/find /var/log/init/ -mindepth 1 -maxdepth 1 |
+  while read; do /bin/mv $REPLY{,.old}; done
+  /etc/init.d/rcS
+  /sbin/telinit $REPLY
+  exit
+ }
 
-critical(){
-alert(){
- short(){ echo -en "\a"; }
-  long(){ for ((CX=0;CX<35;CX++)); do echo -en "\a"; sleep 0.0016; done; }
- pause(){ sleep 0.5; }
+ critical(){
+  alert(){
+   short(){ echo -en "\a"; }
+    long(){ for ((CX=0;CX<35;CX++)); do echo -en "\a"; sleep 0.0016; done; }
+   pause(){ sleep 0.5; }
 
- S(){ echo -n "S"; short; pause; short; pause; short; pause; pause; }
- O(){ echo -n "O"; long;  pause; long;  pause; long;  pause; pause; }
+   S(){ echo -n "S"; short; pause; short; pause; short; pause; pause; }
+   O(){ echo -n "O"; long;  pause; long;  pause; long;  pause; pause; }
 
- S; O; S; echo; sleep 1; S; O; S;
-}
+   S; O; S; echo; sleep 1; S; O; S;
+  }
 
-warn(){
- echo "/etc/init.d/$1 reported an error"
- echo "reboot/shutdown request denied"
- echo "Rebounded to runlevel 3"
-}
+  warn(){
+   echo "/etc/init.d/$1 reported an error"
+   echo "reboot/shutdown request denied"
+   echo "Rebounded to runlevel 3"
+  }
 
-deny(){ warn $1 | tee -a /etc/issue.rootfs; alert; REPLY=3; rebound; }
+  deny(){ warn $1 | tee -a /etc/issue.rootfs; alert; REPLY=3; rebound; }
 
-   if [ -f /var/log/init/failed/extlinux/stop  ]; then deny extlinux
- elif [ -f /var/log/init/failed/initramfs/stop ]; then deny initramfs
+    if [ -f /var/log/init/failed/extlinux/stop  ]; then deny extlinux
+  elif [ -f /var/log/init/failed/initramfs/stop ]; then deny initramfs
+  fi
+ }
+
+ if   log_warning_msg "Final check begins"; critical
+ then log_success_msg "Final check completed"
+ else log_failure_msg "Final check failed"
  fi
-}
-
-if   log_warning_msg "Final check begins"; critical
-then log_success_msg "Final check completed"
-else log_failure_msg "Final check failed"
-fi
-
 }
diff --git a/trunk/grimoire/init-scripts.d/init.d/fsck b/trunk/grimoire/init-scripts.d/init.d/fsck
--- a/trunk/grimoire/init-scripts.d/init.d/fsck
+++ b/trunk/grimoire/init-scripts.d/init.d/fsck
@@ -2,9 +2,10 @@
 
 ### BEGIN INIT INFO
 # Default-Mode: 500
-# Required-Start: fstab root-ro
+# Required-Start: fstab
+# Should-Start: root-ro
 # Should-Start: cryptsetup dmsetup hwclock loadkeys mapper mdadm udev vgchange 
-# Default-Start: S
+# Default-Start: S 1 2 3 4 5
 # Short-Description: checks local filesystems during boot
 ### END INIT INFO
 
@@ -24,6 +25,23 @@ start(){
    log_failure_msg 'fsck failed' 1>/dev/console 2>&1
    log_failure_msg 'Repair file systems by running /sbin/fsck' 1>/dev/console 2>&1
    sulogin -t 120 1>/dev/console 2>&1 0</dev/console
+  fi
+ }
+
+ fsc(){
+  local FORCE
+  if grep -q fastboot  /proc/cmdline; then return;   fi
+  if grep -q forcefsck /proc/cmdline; then FORCE=-f; fi
+
+  if   [ ramfs == "$( /bin/stat -f -c %T / )" ]
+  then FSTAB_FILE=/etc/fstab.rootfs \
+       fsck -C -A -p $FORCE 1>/dev/console 2>&1 0</dev/console
+  else fsck -C -A -p $FORCE 1>/dev/console 2>&1 0</dev/console
+  fi
+  if [ $? -gt 1 ]; then
+   log_failure_msg 'fsck failed' 1>/dev/console 2>&1
+   log_failure_msg 'Repair file systems by running /sbin/fsck' 1>/dev/console 2>&1
+   sulogin -t 60 1>/dev/console 2>&1 0</dev/console
   fi
  }
 
diff --git a/trunk/grimoire/init-scripts.d/init.d/var_tmp b/trunk/grimoire/init-scripts.d/init.d/var_tmp
--- a/trunk/grimoire/init-scripts.d/init.d/var_tmp
+++ b/trunk/grimoire/init-scripts.d/init.d/var_tmp
@@ -7,36 +7,39 @@
 ### BEGIN INIT INFO
 # Default-Mode: 500
 # Required-Start: $local_fs
-# Default-Start: 1 2 3 4 5
-# Short-Description: creates /var/tmp/ and assigns proper mode and ownership
+# Should-Start: tmp
+# Default-Start: S 1 2 3 4 5
+# Short-Description: validates {,/var}/tmp
 ### END INIT INFO
+
+(( UID == 0 )) || exit 0
 
 . /lib/lsb/init-functions
 
 only start
 name /var/tmp
 
-chkdir(){
- if    ! [ -d /var/tmp ]; then
-  if   log_warning_msg "rm -f /var/tmp && mkdir -pm 1777 /var/tmp/" &&
-                        rm -f /var/tmp && mkdir -pm 1777 /var/tmp/
-  then log_success_msg "/var/tmp/ created"
-  else log_failure_msg "/var/tmp/ creation failed"; return 1
-  fi
- elif    [ -d /var/tmp ] &&
-       ! [ -n "$( find /var/tmp -maxdepth 0 -uid 0 -gid 0 -perm 1777 )" ]
- then
-  if   log_warning_msg "chown root:root /var/tmp/ && chmod 1777 /var/tmp/" &&
-                        chown root:root /var/tmp/ && chmod 1777 /var/tmp/
-  then log_success_msg "/var/tmp/ ownership and mode adjusted"
-  else log_failure_msg "/var/tmp/ ownership and mode adjustment failed"; return 1
-  fi
+agu(){ [ "1777 0 0" == "$( /bin/stat -c "%a %g %u" "$1" )" ]; }
+
+init_tmp(){
+ if   ! [ -d $1 ]; then /bin/mkdir -pm 1777  "$1"
+ elif ! agu  $1  ; then /bin/chmod     1777  "$1"
+                        /bin/chown root:root "$1"
  fi
 }
 
 start(){
- if   log_warning_msg "/var/tmp/ existence ownership mode checking"; chkdir
- then log_success_msg "/var/tmp/ verified"
- else log_failure_msg "/var/tmp/ improper"
+ local r
+
+ if   log_warning_msg "/var/tmp/ validating"; init_tmp /var/tmp/
+ then log_success_msg "/var/tmp/ validated"
+ else log_failure_msg "/var/tmp/ validation failed"; r=1
  fi
+
+ if   log_warning_msg "/tmp/ validating"; init_tmp /tmp/
+ then log_success_msg "/tmp/ validated"
+ else log_failure_msg "/tmp/ validation failed"; r=1
+ fi
+
+ return $r
 }
diff --git a/trunk/grimoire/linux-firmware b/trunk/grimoire/linux-firmware
--- a/trunk/grimoire/linux-firmware
+++ b/trunk/grimoire/linux-firmware
@@ -1,23 +1,83 @@
-# tarball no longer available for download,
-# To generate I/R without git installed
-# with base git
-# omitted when sorcerer-installer or sorcerer-iso9660 is installed.
+with base    linux-config
+with role    data
+with trait   firmware
+with info    last 20130321
+with info    home http://www.kernel.org/
+with info    cite 'compiles and installs modules for source in /usr/src/linux/'
 
-with version_year_month
-#with version stable 20120816 20110818
-[ -f "$INSTALL_LOGS/sorcerer-installer" ] ||
-[ -f "$INSTALL_LOGS/sorcerer-iso9660"   ] ||
-with base    git
-with role    kernel
-with trait   archive_off firmware
-with source  stable linux-firmware-$VERSION.tar master git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
-#   source $KERNEL_URL pub/linux/kernel/people/dwmw2/firmware/linux-firmware-$VERSION.tar.bz2
-#   source http://sources.silverice.org/linux-firmware/$VERSION/linux-firmware-$VERSION.tar.xz
-with info    last 20120816
-with info    home http://git.kernel.org/?p=linux/kernel/git/dwmw2/linux-firmware.git
-with info    cite 'free and non free firmware for linux kernel hardware drivers'
+kversion(){
+ local m=/usr/src/linux/Makefile
+
+ if   ! [ -f $m ]
+ then with version stable uncertain; with trait broke; return
+ fi
+
+ local v="s:^VERSION=::p;d"
+ local p="s:^PATCHLEVEL=::p;d"
+ local s="s:^SUBLEVEL=::p;d"
+ local e="s:^EXTRAVERSION=::p;d"
+ local c="s: ::g;"
+
+ v=$( sed "$c $v" $m )
+ p=$( sed "$c $p" $m )
+ s=$( sed "$c $s" $m )
+ e=$( sed "$c $e" $m )
+
+ [ -n "$p" ] && v+=".$p"
+ [ -n "$s" ] && v+=".$s"
+ [ -n "$e" ] && v+=".$e"
+
+ with version stable "$v"
+}
+
+kversion
+
 
 build(){
- mkdir -pvm 755 $DESTDIR/lib/firmware
- cp    -a   *   $DESTDIR/lib/firmware/
+ xz_modules(){
+  local KO="$DESTDIR/lib/modules/$VERSION$1/kernel/"
+  echo "xz compressing modules"
+  find "$KO" -type f -size +4096c -name \*.ko -printf '%p\t%s\n' |
+  while read file size; do
+   xz -f -M 25% --lzma2=dict=$size,mf=bt4,nice=273 "$file" &&
+   ln     "$file"{.xz,} &&
+   unlink "$file.xz"
+  done
+ }
+
+ strip_modules(){
+  find $DESTDIR/lib/modules/$VERSION$1/kernel -type f -name \*.ko |
+  xargs --max-lines=256 strip --strip-unneeded
+ }
+
+ compile_and_install(){
+  local    d=/usr/src/linux
+  local m=$d/Makefile
+  local c=$d/.config.custom
+  local s=$d/.config.stock
+
+  if ! [ -f $m ]; then
+   echo "$m is missing"
+   echo "Try casting linux-source first"
+   return 1
+  elif [ -f $c ]; then cp $c .config
+  elif [ -f $s ]; then cp $s .config
+  else
+   echo "$c does not exist"
+   echo "$s does not exist"
+   echo "$c or $s must exist"
+   echo "try casting linux-config first"
+   return 1
+  fi
+
+  cd /usr/src/linux/ &&
+  make distclean &&
+  yes '' |
+  make O="$BUILD_DIR" oldconfig &&
+# make O="$BUILD_DIR" silentoldconfig &&
+  make O="$BUILD_DIR" firmware_install INSTALL_MOD_PATH="$DESTDIR" &&
+  cd     "$BUILD_DIR"
+ }
+
+ compile_and_install
 }
diff --git a/trunk/grimoire/linux-headers b/trunk/grimoire/linux-headers
--- a/trunk/grimoire/linux-headers
+++ b/trunk/grimoire/linux-headers
@@ -1,57 +1,82 @@
-# Keep the version of linux-headers the same
-# as the lowest version supported by the linux-2.6* spells
-# but do not back it up to 2.6.27 since 2.6.30 has been running fine.
-
-with version stable	3.8.4		3.8.3		3.8.2		3.8.1		3.8.0		3.7.10		3.7.9		3.7.8
-with version 3.8.x	3.8.4		3.8.3		3.8.2		3.8.1		3.8.0
-with version 3.7.x	3.7.10		3.7.9		3.7.8		3.7.7		3.7.6		3.7.5		3.7.4		3.7.3		3.7.2		3.7.1		3.7.0
-with version 3.6.x	3.6.11		3.6.10		3.6.9		3.6.8		3.6.7		3.6.6		3.6.5		3.6.4		3.6.3		3.6.2		3.6.1		3.6
-with version 3.5.x	3.5.7		3.5.6		3.5.5		3.5.4		3.5.3		3.5.2		3.5.1		3.5
-with version 3.4.x	3.4.35		3.4.34		3.4.33		3.4.32		3.4.31		3.4.30		3.4.29		3.4.28		3.4.27		3.4.26		3.4.25		3.4.24		3.4.23		3.4.22		3.4.21		3.4.20		3.4.19		3.4.18		3.4.17		3.4.16		3.4.15		3.4.14		3.4.13		3.4.12		3.4.11		3.4.10		3.4.9		3.4.8		3.4.7		3.4.6		3.4.5		3.4.4		3.4.3		3.4.2		3.4.1		3.4
-with version 3.3.x	3.3.8		3.3.7		3.3.6		3.3.5		3.3.4		3.3.3		3.3.2		3.3.1		3.3
-with version 3.2.x	3.2.40		3.2.39		3.2.38		3.2.37		3.2.36		3.2.35		3.2.34		3.2.33		3.2.32		3.2.31		3.2.30		3.2.29		3.2.28		3.2.27		3.2.26		3.2.25		3.2.24		3.2.23		3.2.22		3.2.21		3.2.20		3.2.19		3.2.18		3.2.17		3.2.16		3.2.15		3.2.14		3.2.13		3.2.11		3.2.10		3.2.9		3.2.8		3.2.7		3.2.6		3.2.5		3.2.4		3.2.3		3.2.2		3.2.1		3.2
-with version "git 3.2.y"	3.2.40	3.2.39		3.2.38		3.2.37		3.2.36		3.2.35		3.2.34		3.2.33		3.2.32		3.2.31		3.2.30		3.2.29		3.2.28		3.2.27		3.2.26		3.2.25		3.2.24		3.2.23		3.2.22		3.2.21		3.2.20		3.2.19		3.2.18		3.2.17		3.2.16		3.2.15		3.2.14		3.2.13		3.2.11		3.2.10		3.2.9		3.2.8		3.2.7		3.2.6		3.2.5		3.2.4		3.2.3		3.2.2		3.2.1		3.2
-with version 3.1.x	3.1.10		3.1.9		3.1.6		3.1.4		3.1.3		3.1.2		3.1.1		3.1
-with version 3.0.x	3.0.68		3.0.67		3.0.66		3.0.65		3.0.64		3.0.63		3.0.62		3.0.61		3.0.60		3.0.59		3.0.58		3.0.57		3.0.56		3.0.55		3.0.54		3.0.53		3.0.52		3.0.51		3.0.50		3.0.49		3.0.47		3.0.46		3.0.45		3.0.44		3.0.43		3.0.42		3.0.41		3.0.40		3.0.39		30.0.38		3.0.37		3.0.36		3.0.35		3.0.34		3.0.33		3.0.32		3.0.31		3.0.30		3.0.29		3.0.28		3.0.27		3.0.26		3.0.25		3.0.24		3.0.17		3.0.9		3.0.8		3.0.4		3.0.3		3.0.2		3.0.1		3.0
-with version 2.6.39.x	2.6.39.4	2.6.39.3	2.6.39.2	2.6.39.1
-with version 2.6.38.x	2.6.38.8	2.6.38.6	2.6.38.5	2.6.38.4	2.6.38.3
-with version 2.6.37.x     2.6.37.6	2.6.37.4	2.6.37.3	2.6.36.3
-with version 2.6.36.x	2.6.36.4	2.6.36.3	2.6.36.2	2.6.36.1
-with version 2.6.35.x	2.6.35.14	2.6.35.13	2.6.35.12	2.6.35.11	2.6.35.10
-with version 2.6.34.x	2.6.34.14	2.6.34.13	2.6.34.12	2.6.34.11	2.6.34.10	2.6.34.9	2.6.34.8
-with version 2.6.32.x	2.6.32.60	2.6.32.59	2.6.32.41	2.6.32.40	2.6.32.28	2.6.32.24
-with version 2.6.30.x	2.6.30.10	2.6.30.9	2.6.30.8
-with version 2.6.27.x	2.6.27.62	2.6.27.59	2.6.27.58	2.6.27.57	2.6.27.54
+with base    linux-config
 with role    development
-with trait   solo
+with trait   console solo
 with info    last 20130321
-with source  stable	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
-with source  3.8.x	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
-with source  3.7.x	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
-with source  3.6.x	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
-with source  3.5.x	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
-with source  3.4.x	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
-with source  3.3.x	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
-with source  3.2.x	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
-with source  3.1.x	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
-with source  3.0.x	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
-with source  2.6.39.x	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
-with source  2.6.38.x	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
-with source  2.6.37.x	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
-with source  2.6.36.x	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
-with source  2.6.35.x	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
-with source  2.6.34.x	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
-with source  2.6.33.x	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
-with source  2.6.32.x	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
-with source  2.6.30.x	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
-with source  2.6.27.x	$KERNEL_URL pub/linux/kernel/v${VERSION:0:1}.x/linux-$VERSION.tar.xz
+with info    home http://www.kernel.org/
+with info    cite 'installs linux header files'
+
+kversion(){
+ local m=/usr/src/linux/Makefile
+
+ if   ! [ -f $m ]
+ then with version stable uncertain; with trait broke; return
+ fi
+
+ local v="s:^VERSION=::p;d"
+ local p="s:^PATCHLEVEL=::p;d"
+ local s="s:^SUBLEVEL=::p;d"
+ local e="s:^EXTRAVERSION=::p;d"
+ local c="s: ::g;"
+
+ v=$( sed "$c $v" $m )
+ p=$( sed "$c $p" $m )
+ s=$( sed "$c $s" $m )
+ e=$( sed "$c $e" $m )
+
+ [ -n "$p" ] && v+=".$p"
+ [ -n "$s" ] && v+=".$s"
+ [ -n "$e" ] && v+=".$e"
+
+ with version stable "$v"
+}
+
+kversion
+
 
 build(){
- rm -rf Documentation
- make headers_install &&
- mkdir -pvm 755       $DESTDIR/usr/include  &&
- cp -av usr/include/* $DESTDIR/usr/include/ &&
- find $DESTDIR/usr/include -type d | xargs --max-lines=256 chmod 755 &&
- find $DESTDIR/usr/include -type f | xargs --max-lines=256 chmod 644 &&
- find $DESTDIR/usr/include         | xargs --max-lines=256 chown root:root
+
+ install_header(){
+  mkdir   -vm 755 -p                                     "$DESTDIR"/usr/include/{asm,linux}/
+  install -vm 644 include/generated/asm-offsets.h        "$DESTDIR"/usr/include/asm/
+  install -vm 644 include/generated/{autoconf,compile}.h "$DESTDIR"/usr/include/linux/
+  cp      -av usr/include/*                              "$DESTDIR"/usr/include/
+  find  "$DESTDIR" -type f -name \*.cmd     | xargs --max-lines=256 rm -f
+  find  "$DESTDIR" -type f -name \*.install | xargs --max-lines=256 rm -f
+  find  "$DESTDIR" -type d                  | xargs --max-lines=256 chmod 755
+  find  "$DESTDIR" -type f                  | xargs --max-lines=256 chmod 644
+  chown -R root:root "$DESTDIR"
+  true
+ }
+
+ compile_and_install(){
+  local    d=/usr/src/linux
+  local m=$d/Makefile
+  local c=$d/.config.custom
+  local s=$d/.config.stock
+
+  if ! [ -f $m ]; then
+   echo "$m is missing"
+   echo "Try casting linux-source first"
+   return 1
+  elif [ -f $c ]; then cp $c .config
+  elif [ -f $s ]; then cp $s .config
+  else
+   echo "$c does not exist"
+   echo "$s does not exist"
+   echo "$c or $s must exist"
+   echo "try casting linux-config first"
+   return 1
+  fi
+
+  cd /usr/src/linux/ &&
+  make distclean &&
+  yes '' |
+  make O="$BUILD_DIR" oldconfig &&
+# make O="$BUILD_DIR" silentoldconfig &&
+  make O="$BUILD_DIR" headers_install prepare &&
+  cd     "$BUILD_DIR" &&
+  install_header
+ }
+
+ compile_and_install
 }
