Updates

diff --git a/trunk/grimoire/sorcery b/trunk/grimoire/sorcery
--- a/trunk/grimoire/sorcery
+++ b/trunk/grimoire/sorcery
@@ -1,11 +1,12 @@
-if    grep      "/root/.sorcery"  /etc/fstab  |
-      sed       "s:#.*::"                     |
-      grep  -q  "nr_inodes=[2-4]m"
-then  VERSION=( "thaumaturgy-20060618-0" "thaumaturgy-20060617-0" "thaumaturgy-20060608-0" "thaumaturgy-20060607-2" "thaumaturgy-20060601-0" "thaumaturgy-20060531-3" "thaumaturgy-20060530-0" "thaumaturgy-20060529-0" "thaumaturgy-20060528-7" "thaumaturgy-20060527-1" "thaumaturgy-20060526-2" "thaumaturgy-20060524-0" "thaumaturgy-20060523-3" "thaumaturgy-20060522-4" "thaumaturgy-20060521-4" "thaumaturgy-20060518-0" "thaumaturgy-20060516-0" "thaumaturgy-20060513-1" "thaumaturgy-20060512-0" "thaumaturgy-20060508-1" "thaumaturgy-20060507-0" "thaumaturgy-20060506-C" "thaumaturgy-20060503-2" "thaumaturgy-20060503-1" "thaumaturgy-20060503-0" "thaumaturgy-20060501-0" )
-else  VERSION=( "thaumaturgy-20060618-0" "thaumaturgy-20060617-0" "thaumaturgy-20060608-0" "thaumaturgy-20060607-2" "thaumaturgy-20060601-0" "thaumaturgy-20060531-3" "thaumaturgy-20060530-0" "thaumaturgy-20060529-0" "thaumaturgy-20060528-7" "thaumaturgy-20060527-1" "thaumaturgy-20060526-2" "thaumaturgy-20060524-0" "thaumaturgy-20060523-3" "thaumaturgy-20060522-4" "thaumaturgy-20060521-4" "thaumaturgy-20060518-0" "thaumaturgy-20060516-0" "thaumaturgy-20060513-1" "thaumaturgy-20060512-0" "thaumaturgy-20060508-1" "thaumaturgy-20060507-0" "thaumaturgy-20060506-C" "thaumaturgy-20060503-2" "thaumaturgy-20060503-1" "thaumaturgy-20060503-0" "thaumaturgy-20060501-0" )
-   echo  "nr_inodes=2m is now required for /root/.sorcery in /etc/fstab"  1>&2
-   echo  "Please modify /etc/fstab and mount -o,remount /root/.sorcery"   1>&2
-fi
+   VERSION=( "thaumaturgy-20060618-0" "thaumaturgy-20060617-0" "thaumaturgy-20060608-0" "thaumaturgy-20060607-2" "thaumaturgy-20060601-0" "thaumaturgy-20060531-3" "thaumaturgy-20060530-0" "thaumaturgy-20060529-0" "thaumaturgy-20060528-7" "thaumaturgy-20060527-1" "thaumaturgy-20060526-2" "thaumaturgy-20060524-0" "thaumaturgy-20060523-3" "thaumaturgy-20060522-4" "thaumaturgy-20060521-4" "thaumaturgy-20060518-0" "thaumaturgy-20060516-0" "thaumaturgy-20060513-1" "thaumaturgy-20060512-0" "thaumaturgy-20060508-1" "thaumaturgy-20060507-0" "thaumaturgy-20060506-C" "thaumaturgy-20060503-2" "thaumaturgy-20060503-1" "thaumaturgy-20060503-0" "thaumaturgy-20060501-0" )
+# if    grep      "/root/.sorcery"  /etc/fstab  |
+#       sed       "s:#.*::"                     |
+#       grep  -q  "nr_inodes=[2-4]m"
+# then  VERSION=( "thaumaturgy-20060618-0" "thaumaturgy-20060617-0" "thaumaturgy-20060608-0" "thaumaturgy-20060607-2" "thaumaturgy-20060601-0" "thaumaturgy-20060531-3" "thaumaturgy-20060530-0" "thaumaturgy-20060529-0" "thaumaturgy-20060528-7" "thaumaturgy-20060527-1" "thaumaturgy-20060526-2" "thaumaturgy-20060524-0" "thaumaturgy-20060523-3" "thaumaturgy-20060522-4" "thaumaturgy-20060521-4" "thaumaturgy-20060518-0" "thaumaturgy-20060516-0" "thaumaturgy-20060513-1" "thaumaturgy-20060512-0" "thaumaturgy-20060508-1" "thaumaturgy-20060507-0" "thaumaturgy-20060506-C" "thaumaturgy-20060503-2" "thaumaturgy-20060503-1" "thaumaturgy-20060503-0" "thaumaturgy-20060501-0" )
+# else  VERSION=( "thaumaturgy-20060618-0" "thaumaturgy-20060617-0" "thaumaturgy-20060608-0" "thaumaturgy-20060607-2" "thaumaturgy-20060601-0" "thaumaturgy-20060531-3" "thaumaturgy-20060530-0" "thaumaturgy-20060529-0" "thaumaturgy-20060528-7" "thaumaturgy-20060527-1" "thaumaturgy-20060526-2" "thaumaturgy-20060524-0" "thaumaturgy-20060523-3" "thaumaturgy-20060522-4" "thaumaturgy-20060521-4" "thaumaturgy-20060518-0" "thaumaturgy-20060516-0" "thaumaturgy-20060513-1" "thaumaturgy-20060512-0" "thaumaturgy-20060508-1" "thaumaturgy-20060507-0" "thaumaturgy-20060506-C" "thaumaturgy-20060503-2" "thaumaturgy-20060503-1" "thaumaturgy-20060503-0" "thaumaturgy-20060501-0" )
+#    echo  "nr_inodes=2m is now required for /root/.sorcery in /etc/fstab"  1>&2
+#    echo  "Please modify /etc/fstab and mount -o,remount /root/.sorcery"   1>&2
+# fi
   CATEGORY="utility"
  ATTRIBUTE="noheal solo sorcery"
     SOURCE="sorcery-$VERSION.tar.bz2"
