Updates

diff --git a/trunk/grimoire/vim b/trunk/grimoire/vim
--- a/trunk/grimoire/vim
+++ b/trunk/grimoire/vim
@@ -1,21 +1,21 @@
-   VERSION=( "7.0" "6.4" "6.3.085" "6.3.076" "6.3.071" "6.3.062" "6.3.061" "6.3.047" "6.3.016" "6.3.014" "6.3.001" "6.3" "6.2.532" )
-      SAFE=( "7.0" "6.4" )
+   VERSION=( "7.0.017" "6.4" "6.3.085" "6.3.076" "6.3.071" "6.3.062" "6.3.061" "6.3.047" "6.3.016" "6.3.014" "6.3.001" "6.3" "6.2.532" )
+      SAFE=( "7.0.017" "7.0" "6.4" )
     IGNORE="\-rt\|-src\|6\.[0-4][1-2]"
   CATEGORY="utility/editor"
  ATTRIBUTE="console x11"
     SOURCE=( "vim-${VERSION:0:3}.tar.bz2"
              "vim-${VERSION:0:3}-lang.tar.gz" )
-#   SCX=2
-#   for  ((PCX=1;PCX<10;PCX++));  do
-#     SOURCE[$SCX]="${VERSION:0:3}.00$PCX"
-#     ((  SCX++  ))
-#   done
+    SCX=2
+    for  ((PCX=1;PCX<10;PCX++));  do
+      SOURCE[$SCX]="${VERSION:0:3}.00$PCX"
+      ((  SCX++  ))
+    done
 # # for  ((PCX=10;PCX<100;PCX++));  do
-#   for  ((PCX=10;PCX<86;PCX++));  do
-#     SOURCE[$SCX]="${VERSION:0:3}.0$PCX"
-#     ((  SCX++  ))
-#   done
-# # for  ((PCX=100;PCX<=${VERSION:4:7};PCX++));  do
+    for  ((PCX=10;PCX<=17;PCX++));  do
+      SOURCE[$SCX]="${VERSION:0:3}.0$PCX"
+      ((  SCX++  ))
+    done
+  # for  ((PCX=100;PCX<=${VERSION:4:7};PCX++));  do
 # #   SOURCE[$SCX]="${VERSION:0:3}.$PCX"
 # #   ((  SCX++  ))
 # # done
@@ -30,7 +30,7 @@
   HOMEPAGE="http://vim.sourceforge.net/"
   EPROVIDE="vi"
    PROVIDE="console-editor"
-  ESTIMATE="183"
+  ESTIMATE="1040"
       DESC="vim is an improved version of vi.
 VIM adds many of the features that you would expect in an editor:
 Unlimited undo, syntax coloring, split windows, visual selection,
@@ -38,18 +38,17 @@ graphical user interface (read: menus, mouse control, scrollbars,
 text selection), and much much more."
 
 build()  {
-# echo  "Patches for the win/mac sources will fail to apply."
-# echo  "Do not worry about failed hunks."
+  echo  "Patches for the win/mac sources will fail to apply."
+  echo  "Do not worry about failed hunks."
 
-# CX=2
-# while  [  -n                 "${SOURCE[$CX]}"  ];  do
-# # bzcat  $(  guess_filename  "${SOURCE[$CX]}"  )  |  patch  -p0
-#     cat  $(  guess_filename  "${SOURCE[$CX]}"  )  |  patch  -p0
-#   ((  CX++  ))
-# done
+  CX=2
+  while  [  -n               "${SOURCE[$CX]}"  ];  do
+    cat  $(  guess_filename  "${SOURCE[$CX]}"  )  |  patch  -p0
+    ((  CX++  ))
+  done
 
-default_build  &&
-if    !  [  -e       /bin/vi  ]
-then  ln    -s  vim  /bin/vi
-fi
+  default_build  &&
+  if    !  [  -e       /bin/vi  ]
+  then  ln    -s  vim  /bin/vi
+  fi
 }
