Updates

diff --git a/trunk/grimoire/vim b/trunk/grimoire/vim
--- a/trunk/grimoire/vim
+++ b/trunk/grimoire/vim
@@ -1,26 +1,26 @@
-   VERSION=( 7.1.175 7.1.145 7.1.138 7.1.116 )
-      SAFE=( 7.1.175 7.1.145 7.1.138 7.1.116 )
+   VERSION=( 7.1.266 7.1.175 7.1.145 7.1.138 7.1.116 )
+      SAFE=( 7.1.266 7.1.175 7.1.145 7.1.138 7.1.116 )
     IGNORE='\-rt\|-src\|6\.[0-4][1-2]'
   CATEGORY='utility/editor'
  ATTRIBUTE='console x11'
     SOURCE=( "vim-${VERSION:0:3}.tar.bz2"
              "vim-${VERSION:0:3}-lang.tar.gz" )
     SCX=2
-     for  ((PCX=1;PCX<10;PCX++));  do
-#    for  ((PCX=1;PCX<=${VERSION:4:7};PCX++));  do
-       SOURCE[$SCX]="${VERSION:0:3}.00$PCX"
-       ((  SCX++  ))
+     for ((PCX=1;PCX<10;PCX++)); do
+#    for ((PCX=1;PCX<=${VERSION:4:7};PCX++)); do
+      SOURCE[$SCX]="${VERSION:0:3}.00$PCX"
+      (( SCX++ ))
     done
-    for  ((PCX=10;PCX<100;PCX++));  do
-#    for  ((PCX=10;PCX<${VERSION:5:7};PCX++));  do
-       SOURCE[$SCX]="${VERSION:0:3}.0$PCX"
-       ((  SCX++  ))
+    for ((PCX=10;PCX<100;PCX++)); do
+#   for ((PCX=10;PCX<${VERSION:5:7};PCX++)); do
+     SOURCE[$SCX]="${VERSION:0:3}.0$PCX"
+     (( SCX++ ))
     done
-    for  ((PCX=100;PCX<=${VERSION:4:7};PCX++));  do
-      SOURCE[$SCX]="${VERSION:0:3}.$PCX"
-      ((  SCX++  ))
+    for ((PCX=100;PCX<=${VERSION:4:7};PCX++)); do
+     SOURCE[$SCX]="${VERSION:0:3}.$PCX"
+     (( SCX++ ))
     done
-    unset  SCX  PCX  VPAT
+    unset SCX PCX VPAT
        URL=( "ftp://ftp.vim.org/pub/vim/unix/"
              "ftp://ftp.vim.org/pub/vim/extra/"
              "ftp://ftp.vim.org/pub/vim/patches/${VERSION:0:3}/" )
@@ -30,25 +30,25 @@
   HOMEPAGE='http://vim.sourceforge.net/'
 # EPROVIDE='vi'
    PROVIDE='console-editor'
-  ESTIMATE='1700'
+  ESTIMATE='2000'
       DESC='vim is an improved version of vi.
 VIM adds many of the features that you would expect in an editor:
 Unlimited undo, syntax coloring, split windows, visual selection,
 graphical user interface (read: menus, mouse control, scrollbars,
 text selection), and much much more.'
 
-build()  {
-  echo  'Patches for the win/mac sources will fail to apply.'
-  echo  'Do not worry about failed hunks.'
+build(){
+ echo 'Patches for the win/mac sources will fail to apply.'
+ echo 'Do not worry about failed hunks.'
 
-  CX=2
-  while  [  -n                                   "${SOURCE[$CX]}"  ];  do
-    patch   -p0  <  $SOURCE_CACHE/$SPELL/$VERSION/${SOURCE[$CX]}
-    ((  CX++  ))
-  done
+ CX=2
+ while  [ -n                               "${SOURCE[$CX]}" ]; do
+  patch -p0 < $SOURCE_CACHE/$SPELL/$VERSION/${SOURCE[$CX]}
+  (( CX++ ))
+ done
 
-  default_build  &&
-  if    !  [  -e       /usr/bin/vi  ]
-  then  ln    -s  vim  /usr/bin/vi
-  fi
+ default_build &&
+ if   !  [ -e     /usr/bin/vi ]
+ then ln   -s vim /usr/bin/vi
+ fi
 }
