good progress

diff --git a/trunk/grimoire/tomoyo-tools.d/init.d/tomoyo-loadpolicy-sorcerer b/trunk/grimoire/tomoyo-tools.d/init.d/tomoyo-loadpolicy-sorcerer
--- a/trunk/grimoire/tomoyo-tools.d/init.d/tomoyo-loadpolicy-sorcerer
+++ b/trunk/grimoire/tomoyo-tools.d/init.d/tomoyo-loadpolicy-sorcerer
@@ -5,26 +5,51 @@
 # For use with the distribution sorcerer only!
 
 ### BEGIN INIT INFO
-# Default-Mode: 500
+# Default-Mode: 510
 # Required-Start: tomoyo-domain
-# Default-Start: 2 3 4 5
+# Default-Start: 1 2 3 4 5
 # Short-Description: loads Sorcerer specific policies for Tomoyo
 ### END INIT INFO
 
 . /lib/lsb/init-functions
 
-only start
+only start status try-restart
 
-start(){
- content(){ find $1 -type f | grep -v "\.svn" | xargs -r --max-lines=64 cat; }
-
- load_policies(){
-  content /etc/tomoyo/sorcerer/exception | tomoyo-loadpolicy -ef &&
-  content /etc/tomoyo/sorcerer/domain    | tomoyo-loadpolicy -df
+status(){
+ check(){ 
+  [ -f /etc/tomoyo/exception_policy.conf ] && [ -f  /etc/tomoyo/domain_policy.conf ] &&
+  [ -z "$( find /etc/tomoyo/sorcerer -type f -newer /etc/tomoyo/domain_policy.conf )" ]
  }
-
- if   log_warning_msg "Sorcerer specific tomoyo policies loading"; load_policies
- then log_success_msg "Sorcerer specific tomoyo policies loaded"
- else log_failure_msg "Sorcerer specific tomoyo policies not loaded"; return 1
+ if   log_warning_msg "Sorcerer tomoyo policies checking status"; check
+ then log_success_msg "Sorcerer tomoyo policies current";
+ else log_failure_msg "Sorcerer tomoyo policies require concatentation"; return 1
  fi
 }
+
+start(){
+ concat(){
+  cat_pol(){
+   rm -f /etc/tomoyo/{domain,exception}_policy.conf &&
+   cat   /etc/tomoyo/sorcerer/domain/*    > /etc/tomoyo/domain_policy.conf &&
+   cat   /etc/tomoyo/sorcerer/exception/* > /etc/tomoyo/exception_policy.conf
+  }
+  if   log_warning_msg "Sorcerer tomoyo policies concatenating"; cat_pol
+  then log_success_msg "Sorcerer tomoyo policies concatenated"
+  else log_failure_msg "Sorcerer tomoyo policies concatenation error"; return 1
+  fi
+ }
+
+ load_policies(){
+  load(){ tomoyo-loadpolicy ef && tomoyo-loadpolicy df; }
+  if   log_warning_msg "Sorcerer tomoyo policies loading"; load
+  then log_success_msg "Sorcerer tomoyo policies loaded"
+  else log_failure_msg "Sorcerer tomoyo policies not loaded"; return 1
+  fi
+ }
+
+ if   ! status
+ then concat && load
+ fi
+}
+
+try_restart(){ start; }
