Updates

diff --git a/trunk/grimoire/init-scripts.d/init.d.on/depmod b/trunk/grimoire/init-scripts.d/init.d.on/depmod
--- a/trunk/grimoire/init-scripts.d/init.d.on/depmod
+++ b/trunk/grimoire/init-scripts.d/init.d.on/depmod
@@ -13,23 +13,24 @@ if [ "$1" = try-restart ] || ! [ -s /sbin/depmod ]; then exit; fi
 
 . /lib/lsb/init-functions
 
-local MPD
 if   [ -d /etc/modprobe.d ]
 then  MPD=/etc/modprobe.d
 fi
+LM=/lib/modules
 
-find /lib/modules -maxdepth 2 -mindepth 2 -name modules.dep -printf '%P\n' |
+find $LM -maxdepth 2 -mindepth 2 -name kernel -printf '%P\n' |
 sed 's:/.*::' |
 while read REPLY; do
- log_warning_msg "depmod checking /lib/modules/$REPLY/modules.dep"
- find /lib/modules/$REPLY/kernel $MPD -type f -newer \
- /lib/modules/$REPLY/modules.dep | grep -q . &&
- echo "$REPLY"
- log_success_msg "depmod checked  /lib/modules/$REPLY/modules.dep"
+ log_warning_msg "depmod checking $LM/$REPLY/modules.dep"
+ if   ! [ -f $LM/$REPLY/modules.dep ];               then echo "$REPLY"
+ elif find   $LM/$REPLY/kernel $MPD -type f -newer \
+             $LM/$REPLY/modules.dep | grep -q .;     then echo "$REPLY"
+ fi
+ log_success_msg "depmod checked  $LM/$REPLY/modules.dep"
 done |
 while read REPLY; do
- if   log_warning_msg "depmod updating /lib/modules/$REPLY/modules.dep"; depmod -aA $REPLY
- then log_success_msg "depmod updated  /lib/modules/$REPLY/modules.dep"
- else log_failure_msg "depmod failed   /lib/modules/$REPLY/modules.dep"
+ if   log_warning_msg "depmod updating $LM/$REPLY/modules.dep"; depmod -a $REPLY
+ then log_success_msg "depmod updated  $LM/$REPLY/modules.dep"
+ else log_failure_msg "depmod failed   $LM/$REPLY/modules.dep"
  fi
 done
