Smaller init-scripts

diff --git a/trunk/grimoire/init-scripts.d/init.d.on/fsck b/trunk/grimoire/init-scripts.d/init.d.on/fsck
--- a/trunk/grimoire/init-scripts.d/init.d.on/fsck
+++ b/trunk/grimoire/init-scripts.d/init.d.on/fsck
@@ -8,34 +8,29 @@
 # Default-Start: S
 # Default-Stop:
 # Short-Description: fsck checks local filesystems during boot
-# Description: fsck checks local filesystems during boot
 ### END INIT INFO
 
 . /lib/lsb/init-functions
 
-fsc()  {
-  if  [ -f /fastboot      ]; then return;     fi
-  if  [ -f /forcefsck     ]; then FORCE='-f'; fi
-  if  [ "$FSCKFIX" == yes ]; then FIX='-y';
-                             else FIX='-a';   fi
-  fsck  -C  -A  $FIX  $FORCE  &>/dev/console  0</dev/console
-  if [  $?  -gt  1  ];  then
-    log_failure_msg  'fsck failed'  &>/dev/console
-    log_failure_msg  'Repair file systems by running /sbin/fsck'  &>/dev/console
-    sulogin  -t  120  &>/dev/console  0</dev/console
+start(){
+ fsc(){
+  if [ -f /fastboot      ]; then return; fi
+  if [ -f /forcefsck     ]; then FORCE='-f'; fi
+  if [ "$FSCKFIX" == yes ]; then FIX='-y';
+                            else FIX='-a'; fi
+
+  fsck -C -A $FIX $FORCE &>/dev/console 0</dev/console
+  if [ $? -gt 1 ]; then
+   log_failure_msg 'fsck failed' &>/dev/console
+   log_failure_msg 'Repair file systems by running /sbin/fsck' &>/dev/console
+   sulogin -t 120 &>/dev/console 0</dev/console
   fi
+ }
+
+ log_warning_msg 'Local file systems checking'; fsc
+ log_success_msg 'Local file systems checked'
 }
-
-start()  {
-  log_warning_msg  'Local file systems checking'; fsc
-  log_success_msg  'Local file systems checked'
-}
-
-
-help()  {  echo "Usage: $0 {start}" 1>&2;  }
-
-case  $1  in
-        start)  start  ;;
-  try-restart)  :      ;;
-            *)  help   ;;
-esac
+       stop(){ :; }
+    restart(){ :; }
+try_restart(){ :; }
+parse "$@"
