Updates

diff --git a/trunk/grimoire/init-scripts.d/init.d.on/gtk-update-icon-cache b/trunk/grimoire/init-scripts.d/init.d.on/gtk-update-icon-cache
--- a/trunk/grimoire/init-scripts.d/init.d.on/gtk-update-icon-cache
+++ b/trunk/grimoire/init-scripts.d/init.d.on/gtk-update-icon-cache
@@ -6,23 +6,27 @@
 # Short-Description: Updates the icon cache
 ### END INIT INFO
 
-HI=/usr/share/icons/hicolor
-HC=/usr/share/icons/hicolor/icon-theme.cache
-
-up(){
- if   log_warning_msg "$HC Updating"; gtk-update-icon-cache -f -t $HI
- then log_success_msg "$HC Updated"
- else log_failure_msg "Failed to update $HC"
- fi
-}
-
 [ -f /usr/bin/gtk-update-icon-cache ] || return
 
 . /lib/lsb/init-functions
 
-log_warning_msg "$HC Checking"
+IC=icon-theme.cache
 
-  if ! [ -f $HC ]; then up
-elif find $HI -type f -newer $HC | grep -q .; then up
-else log_success_msg "$HC Current"
-fi
+find /usr/share/icons -mindepth 2 -maxdepth 2 \
+     -name index.theme -printf '%h\n' |
+while read REPLY; do
+ log_warning_msg "$IC in $REPLY checking"
+ if ! [ -f $REPLY/$IC ] ||
+    find   $REPLY -type f -newer \
+           $REPLY/$IC | grep -q .
+ then log_warning_msg "$IC in $REPLY not current"; echo "$REPLY"
+ else log_warning_msg "$IC in $REPLY     current"
+ fi
+done |
+while read REPLY; do
+ if   log_warning_msg "$IC in $REPLY Updating"; 
+      gtk-update-icon-cache -f $REPLY
+ then log_success_msg "$IC in $REPLY Updated"
+ else log_failure_msg "$IC in $REPLY Update failed"
+ fi
+done
