bug fixes

diff --git a/trunk/grimoire/install.d/sinstall b/trunk/grimoire/install.d/sinstall
--- a/trunk/grimoire/install.d/sinstall
+++ b/trunk/grimoire/install.d/sinstall
@@ -256,8 +256,11 @@ make_bootloader_conf(){
  /etc/init.d/udevtrigger start
 
  UUID=$( blkid ${PDEVICE[$BB]} 2>/dev/null | cut -d '"' -f2 )
-#echo "boot${TAB}${TAB}${TAB}=${TAB}/dev/disk/by-uuid/$UUID" >> $BL_CONF
- echo "boot${TAB}${TAB}${TAB}=${TAB}\"UUID=$UUID\"" >> $BL_CONF
+echo "boot${TAB}${TAB}${TAB}=${TAB}/dev/disk/by-uuid/$UUID" >> $BL_CONF
+
+# The UUID= notation works on lilo 22.8's command line
+# but when properly written in lilo's configuration file.
+#echo "boot${TAB}${TAB}${TAB}=${TAB}\"UUID=$UUID\"" >> $BL_CONF
 
  BBDEV=${PDEVICE[$BB]}
 
@@ -294,6 +297,12 @@ terror_retry(){
 
 
 transfer_arch(){
+ local NOT_MOUNT=$"Not detecting file system mounted on $TARGET"
+
+ if   ! grep -q $TARGET /proc/mounts
+ then msgbox "$NOT_MOUNT"; allow || return 1
+ fi
+
  local MIR=/media/IR
 
  rm -f /tmp/terror
@@ -332,7 +341,7 @@ transfer_arch(){
  if ! xz -cd;                  then echo "$ED" >> /tmp/terror; fi |
  if ! tar -C $TARGET -ixvpf -; then echo "$ET" >> /tmp/terror; fi
 
- make_fstab > $TARGET/etc/fstab
+ cp /tmp/fstab > $TARGET/etc/fstab
 
  if ! [ -f /tmp/terror ]; then
   read -n 1 -t 900 -p "Press space to continue."
@@ -775,7 +784,9 @@ filesystem_table(){
 
 
  check_root_defined(){
-  root_device | grep -q . || msgbox $"/ Root filesystem required!"
+  if   ! root_device | grep -q .
+  then msgbox $"/ Root filesystem required!"; return 1
+  fi
  }
 
  check_double_device(){
@@ -791,7 +802,7 @@ filesystem_table(){
   )"
 
   if   [ -n "$DUP" ]
-  then msgbox "${DDD}: ${DUP//$LF/ }${LF}${FIX}"
+  then msgbox "${DDD}: ${DUP//$LF/ }${LF}${FIX}"; return 1
   fi
  }
 
@@ -805,9 +816,12 @@ to the fields on a line in /etc/fstab"
  offer_man fstab
 
  while modify_pentry $( get_pcx $( pselect ) ); do : ; done
- check_root_defined
- check_double_device
- true
+
+ if   check_root_defined &&
+      check_double_device
+ then make_fstab > /tmp/fstab
+ else return 1
+ fi
 }
 
 
@@ -954,6 +968,16 @@ get_mk_command(){
  esac
 }
 
+log_eval(){
+ rm -fr /tmp/{err,out}
+ echo > /tmp/err
+
+ if eval "$1"; then rm -f /tmp/err; fi 2>&1 | tee /tmp/out
+ if [ -f /tmp/err ]
+ then cat /tmp/out >> /tmp/initialize_problem.txt; false
+ else cat /tmp/out >> /tmp/initialize_success.txt
+ fi
+}
 
 initialize(){
 
@@ -964,9 +988,9 @@ initialize(){
  FAILURE="No success at creating ${PFILESYSTEM[$1]} on ${PDEVICE[$1]}"
 
  if confirm "$SURE" --defaultno; then
-                 COMMAND="$( get_mk_command "$1" )"
-  if   confirm "$COMMAND" --defaultno &&
-       eval    "$COMMAND"
+                  COMMAND="$( get_mk_command "$1" )"
+  if   confirm  "$COMMAND" --defaultno &&
+       log_eval "$COMMAND"
   then sleep  3; $DIALOG --msgbox "$SUCCESS" 8 50
   else sleep 10; $DIALOG --msgbox "$FAILURE" 8 50; return 1
   fi
@@ -1293,12 +1317,12 @@ run_skill(){
  local LVM=$"logical volume managment;"
  local RAID=$"kernel implemented redundant array of inexpensive disks;"
  local LUKS=$"linux unified key setup;"
- local ALSO=$"and also the option to disregard the installer's enforcement of required menus."
- local NOVICE=$"Novice skill provides enough to accomplish simple installation."
- local EXPERT=$"Expert skill provides: "
+ local ALSO=$"and enforcement of safe order bypass."
+ local NOVICE=$"Novice allows for an uncomplicated installation."
+ local EXPERT=$"Expert provides:"
  local AWESOME=$"Enable expert skill level?"
 
- msgbox "${NOVICE}${LF}${EXPERT}${LVM}${RAID}${LUKS}${ALSO}"
+ msgbox "${NOVICE}${LF}${EXPERT}${LF}${LVM}${LF}${RAID}${LF}${LUKS}${LF}${ALSO}"
 
  if   confirm "$AWESOME" --defaultno
  then SKILL="expert"
@@ -1345,44 +1369,134 @@ allow(){
  local SOON=$"Earlier menus are required."
  local YEAH=$"Disregard and proceed at the risk of grand failure?"
 
- if   [ -n       "$1"     ]; then return
- elif [ expert = "$SKILL" ]; then msgbox "$SOON"; confirm "$YEAH" --defaultno
+ if   [ expert = "$SKILL" ]
+ then msgbox "$SOON"; confirm "$YEAH" --defaultno
  else return 1
  fi
 }
 
-run_reload_fstab(){ if [ -z "$MOUNT" ]; then filesystem_table_load; fi; }
-run_modify_fstab(){ filesystem_table; FSTAB=true; }
-run_init_filesys(){ if allow "$FSTAB"; then filesystem_initialize; FINIT=true; fi; }
-     run_install(){ if allow "$MOUNT"; then transfer_arch 2>&1 | tee /tmp/transfer.txt; INSTALL=true; fi; }
-  run_edit_fstab(){ if allow "$INSTALL"; then edit_fstab; fi; }
-     run_compile(){ if allow "$INSTALL"; then compile_menu; COMPILE=true; fi; }
-       run_mount(){ filesystem_mount; MOUNT=true; }
-      run_umount(){ if allow "$MOUNT"; then filesystem_unmount; MOUNT=; fi; }
-        run_done(){ goodbye; }
+mounted(){ grep -q "$TARGET" /proc/mounts; }
 
+installed(){ [ -f "$TARGET/usr/sbin/cast" ]; }
+
+compiled(){ [ -d "$TARGET/var/log/sorcery/event" ]; }
+
+fstabed(){ [ -f /tmp/fstab ]; }
+
+initalized(){ [ -f /tmp/initialize_success.txt ]; }
+
+
+run_reload_fstab(){
+ if ! mounted
+ then filesystem_table_load
+ fi
+}
+
+
+run_modify_fstab(){ filesystem_table; }
+
+run_init_filesys(){
+ if   fstabed || allow
+ then filesystem_initialize
+ fi
+}
+
+run_install(){    if mounted   || allow; then transfer_arch 2>&1 | tee /tmp/transfer.txt; fi; }
+run_edit_fstab(){ if installed || allow; then edit_fstab;   fi; }
+run_compile(){    if installed || allow; then compile_menu; fi; }
+
+run_mount(){  if ! mounted; then filesystem_mount; fi; }
+run_umount(){ if   mounted; then filesystem_unmount; fi; }
+
+        run_done(){ goodbye; }
        rdy_lsmod(){ echo optional; }
     rdy_modprobe(){ echo optional; }
        rdy_rmmod(){ echo optional; }
-         rdy_mbr(){ if [ "$MBR"        ]; then echo complete; else echo optional; fi; }
-   rdy_partition(){ if [ "$PARTITION"  ]; then echo complete; else echo optional; fi; }
     rdy_vgcreate(){ echo optional; }
     rdy_lvcreate(){ echo optional; }
     rdy_vgremove(){ echo optional; }
     rdy_lvremove(){ echo optional; }
        rdy_mdadm(){ echo optional; }
   rdy_mdadm_stop(){ echo optional; }
-rdy_reload_fstab(){ if   [ -n "$MOUNT"   ]; then echo -n 'too late, '; fi; echo optional; }
-rdy_modify_fstab(){ if   [ -n "$FSTAB"   ]; then echo complete; else echo required; fi; }
-rdy_init_filesys(){ if   [ -n "$FINIT"   ]; then echo complete
-                    elif [ -z "$FSTAB"   ]; then echo 'later, prudent' 
-                                            else echo prudent; fi; }
-       rdy_mount(){ if   [    "$MOUNT"   ]; then echo complete; else if [ -z "$FSTAB"   ]; then echo -n 'later, '; fi; echo required; fi; }
-     rdy_install(){ if   [    "$INSTALL" ]; then echo complete; else if [ -z "$MOUNT"   ]; then echo -n 'later, '; fi; echo required; fi; }
-  rdy_edit_fstab(){ if   [ -z "$INSTALL" ]; then echo -n 'later, '; fi; echo optional; }
-     rdy_compile(){ if   [    "$COMPILE" ]; then echo complete; else if [ -z "$INSTALL" ]; then echo -n 'later, '; fi; echo required; fi; }
-      rdy_umount(){ echo optional; }
-        rdy_done(){ if   [ -z "$COMPILE" ]; then echo -n 'later, '; fi; echo required; }
+
+rdy_mbr(){
+ if   [ "$MBR" ]
+ then echo complete
+ else echo optional
+ fi
+}
+
+rdy_partition(){
+ if   [ "$PARTITION" ]
+ then echo complete
+ else echo optional
+ fi
+}
+
+
+rdy_reload_fstab(){ 
+ if mounted
+ then echo 'optional before mount'
+ else echo 'optional'
+ fi
+}
+
+
+rdy_modify_fstab(){ 
+ if   fstabed
+ then echo complete
+ else echo required
+ fi
+}
+
+rdy_init_filesys(){
+ if   initialized; then echo 'complete'
+ elif fstabed;     then echo 'prudent later' 
+                   else echo 'prudent'
+ fi
+}
+
+rdy_mount(){
+ if   mounted; then echo 'complete'
+ elif fstabed; then echo 'required'
+               else echo 'required later'
+ fi
+}
+
+rdy_install(){
+ if   installed; then echo 'complete'
+ elif mounted;   then echo 'required'
+                 else echo 'required later'
+ fi
+}
+
+rdy_edit_fstab(){
+ if   mounted
+ then echo 'optional'
+ else echo 'optional later'
+ fi
+}
+
+rdy_compile(){
+ if   compiled; then echo 'complete'
+ elif mounted;  then echo 'required'
+                else echo 'required later'
+ fi
+}
+
+rdy_umount(){
+ if   mounted
+ then echo 'optional'
+ else echo 'optional later'
+ fi
+}
+
+rdy_done(){
+ if   compiled
+ then echo 'required'
+ else echo 'required later'
+ fi
+}
 
 
 main_menu_novice(){
@@ -1392,17 +1506,12 @@ Press the Enter key to make a selection."
 
  $DIALOG --item-help --nocancel --default-item "$MAIN" --menu "$HELP" 0 60 10 \
   skill        "$SKILL"                "Select novice or expert menus" \
-  lsmod        "$( rdy_lsmod        )" "list loaded modules" \
-  modprobe     "$( rdy_modprobe     )" "load module" \
-  rmmod        "$( rdy_rmmod        )" "remove loaded module" \
   mbr          "$( rdy_mbr          )" "write bootable master boot record" \
   partition    "$( rdy_partition    )" "create partition on a block device" \
-  reload_fstab "$( rdy_reload_fstab )" "reload incomplete filesystem table" \
   modify_fstab "$( rdy_modify_fstab )" "modify filesystem table" \
   init_filesys "$( rdy_init_filesys )" "initialize filesystems" \
   mount        "$( rdy_mount        )" "mount filesystems" \
   install      "$( rdy_install      )" "install software to new filesystem" \
-  edit_fstab   "$( rdy_edit_fstab   )" "edit /etc/fstab on new root filesystem" \
   compile      "$( rdy_compile      )" "configure, compile and install some software" \
   umount       "$( rdy_umount       )" "unmount filesystems" \
   exit         "$( rdy_done         )" "exit installer"
