bug fixes

diff --git a/trunk/grimoire/init-functions.d/init-functions b/trunk/grimoire/init-functions.d/init-functions
--- a/trunk/grimoire/init-functions.d/init-functions
+++ b/trunk/grimoire/init-functions.d/init-functions
@@ -3,22 +3,18 @@
 # Copyright Kyle Sallee 2005 through 2008.
 # All rights reserved.
 
- NORM="\e[0m"
-  RED="\e[31m"
-GREEN="\e[32m"
- BLUE="\e[34m"
-WHITE="\e[37m"
+NORM="\e[0m"; RED="\e[31m"; GREEN="\e[32m"; BLUE="\e[34m"; WHITE="\e[37m"
 
 S60="                                                            "
 
-log_start()  { echo -n -e "$GREEN * $NORM$1${S60:${#1}}" 1>&2; }
-log_finish() { echo    -e "${BLUE}[$1 ${BLUE}]${NORM}"   1>&2; }
+log_start()  { echo -en "$GREEN * $NORM$1${S60:${#1}}" 1>&2;}
+log_finish() { echo -e  "$BLUE[$1 $BLUE]$NORM" 1>&2;}
 
-log_success_msg() { log_start "$1"; log_finish "$GREEN success"; }
-log_failure_msg() { log_start "$1"; log_finish "$RED failed "; }
-log_warning_msg() { log_start "$1"; log_finish "$WHITE warning"; }
+log_success_msg() { log_start "$1"; log_finish "$GREEN success";}
+log_failure_msg() { log_start "$1"; log_finish "$RED failed ";}
+log_warning_msg() { log_start "$1"; log_finish "$WHITE warning";}
 
-locked() {
+locked(){
  local L S P REPLY
 
  [ -n "$2" ] && L=${#2} &&
@@ -30,7 +26,7 @@ locked() {
  [ "${REPLY:6:$L}" == "$2" ]
 }
 
-pidofproc() {
+pidofproc(){
 
  while
   case $1 in
@@ -60,7 +56,7 @@ pidofproc() {
  fi
 }
 
-killproc() {
+killproc(){
  local PIDF PID BASE PIDS SIGL
 
  while
@@ -90,7 +86,7 @@ killproc() {
  fi
 }
 
-start_daemon() {
+start_daemon(){
  local FORC NICE PIDF BASE PIDS BACK
 
  while
@@ -134,7 +130,7 @@ start_daemon() {
 # $PIDF $LOCK are optional.
 # $OPTS is optional except when mounting
 
-status() {
+status(){
  PIDS="$( pidofproc -p "$PIDF" "$SERV" )"
  if   [ -n "$PIDS" ]; then log_warning_msg "$NAME is running"; return 0
  elif [ -f "$PIDF" ]; then log_warning_msg "$NAME is dead and $PIDF exists"; return 1
@@ -144,36 +140,37 @@ status() {
  fi
 }
 
-stop() {
+stop(){
  if   log_warning_msg "$NAME stopping"; killproc -p "$PIDF" -s 15 "$SERV"
  then log_success_msg "$NAME stopped"
  else log_failure_msg "$NAME not stopped"; status
  fi
 }
 
-start() {
+start(){
 
- starts() {
+ starts(){
   if   log_warning_msg "$NAME starting"; start_daemon -p "$PIDF" "$SERV" $OPTS
   then log_success_msg "$NAME started"
   else log_failure_msg "$NAME not started"; status
   fi
  }
 
- startm() {
-  run() {
+ startm(){
+  run(){
    if   !   [ -d "$NAME" ]
    then mkdir -p "$NAME"; fi &&
    mount $OPTS   "$NAME"
   }
 
-  if    ! sed 's/#.*//' /etc/fstab |
-          grep -qw      "$NAME" &&
-        ! grep -qws     "$NAME" /proc/mounts; then
-   if   log_warning_msg "$NAME mounting"; run
-   then log_success_msg "$NAME mounted"
-   else log_failure_msg "$NAME not mounted"
-   fi
+  stb(){ sed 's/#.*//' /etc/fstab | grep -qw $NAME;}
+  chk(){ case $NAME in /dev|/proc|/sys) return 1;; esac; stb;}
+  mnt(){ grep -qws "$NAME" /proc/mounts;}
+
+  if mnt || chk; then return; fi
+  if   log_warning_msg "$NAME mounting"; run
+  then log_success_msg "$NAME mounted"
+  else log_failure_msg "$NAME not mounted"
   fi
  }
 
@@ -183,15 +180,15 @@ start() {
  esac
 }
 
-    restart() { stop   && sleep 1; start; }
-try_restart() { status && restart; return 0; }
+    restart(){ stop   && sleep 1; start;}
+try_restart(){ status && restart; return 0;}
 
-help() { echo "Usage: $0 {start|stop|status|restart}"; }
+help(){ echo "Usage: $0 {start|stop|status|restart}";}
 
-parse() {
- case "$1" in
-        start)       start ;;
-      restart)     restart ;;
+parse(){
+ case $1 in
+  start) start ;;
+  restart) restart ;;
   try-restart) try_restart ;;
     stop) stop   ;;
   status) status ;;
