Updates

diff --git a/trunk/grimoire/init-functions.d/init-functions b/trunk/grimoire/init-functions.d/init-functions
--- a/trunk/grimoire/init-functions.d/init-functions
+++ b/trunk/grimoire/init-functions.d/init-functions
@@ -1,201 +1,200 @@
-# LSB-compliant init.d scripts for use with the distribution sorcerer only!
-# Copyright Kyle Sallee 2005, 2007.  All rights reserved.
-# The following functions are written as specified by the following URL
-# http://www.linuxbase.org/spec/refspecs/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptfunc.html
+# Functions for LSB-compliant init-scripts
+# For use with sorcerer only!
+# Copyright Kyle Sallee 2005 through 2008.
+# All rights reserved.
 
-
-DEFAULT="\e[0m"
-   BOLD="\e[1m"
-  BLACK="\e[30m"
-    RED="\e[31m"
-  GREEN="\e[32m"
- YELLOW="\e[33m"
-   BLUE="\e[34m"
- VIOLET="\e[35m"
-   CYAN="\e[36m"
-  WHITE="\e[37m"
+ NORM="\e[0m"
+  RED="\e[31m"
+GREEN="\e[32m"
+ BLUE="\e[34m"
+WHITE="\e[37m"
 
 S60="                                                            "
 
-log_start()  {
-  echo  -n  -e  "${GREEN} * ${DEFAULT}"  1>&2
-  echo  -n  -e  "$1"                     1>&2
-  echo  -n      "${S60:${#1}}"           1>&2
+log_start()  { echo -n -e "$GREEN * $NORM$1${S60:${#1}}" 1>&2; }
+log_finish() { echo    -e "${BLUE}[$1 ${BLUE}]${NORM}"   1>&2; }
+
+log_success_msg() { log_start "$1"; log_finish "$GREEN success"; }
+log_failure_msg() { log_start "$1"; log_finish "$RED failed "; }
+log_warning_msg() { log_start "$1"; log_finish "$WHITE warning"; }
+
+locked() {
+ local L S P REPLY
+
+ [ -n "$2" ] && L=${#2} &&
+ [ -n "$1" ] && [ -f  $1 ] &&
+ read P < $1 &&
+ S="/proc/$P/status" &&
+ [ -f   $S ] &&
+ read < $S &&
+ [ "${REPLY:6:$L}" == "$2" ]
 }
 
-log_finish()  {  echo  -e  "${BLUE}[$1 ${BLUE}]${DEFAULT}"  1>&2;  }
+pidofproc() {
 
-log_success_msg()  {
-  log_start  "$1"
-  log_finish "${GREEN} success"
-}
+ while
+  case $1 in
+   -p) PIDF=$2 ;;
+    *) break ;;
+  esac
+ do shift 2
+ done
 
-log_failure_msg()  {
-  log_start  "$1"
-  log_finish "${RED} failed "
-}
+ BASE=${1##*/}
 
-log_warning_msg()  {
-  log_start  "$1"
-  log_finish "${WHITE} warning"
-}
-
-locked()  {
-  local  LEN  STATUS  LINE  LPID
-
-  [  -n  "$2"  ]  &&  LEN=${#2}      &&
-  [  -n  "$1"  ]  &&  [  -f   $1  ]  &&
-  read  LPID  <  $1                  &&
-  STATUS="/proc/$LPID/status"        &&
-  [  -f          $STATUS  ]          &&
-  read  LINE  <  $STATUS             &&
-  [  "${LINE:6:$LEN}"  ==  "$2"   ]
-}
-
-pidofproc()  {
-# pidofproc [-p pidfile] pathname
-
-  local  BASE  PIDF  PIDS
-
-  while
-    case  $1  in
-      -p)  PIDF="$2";  shift  2  ;;
-       *)  false                 ;;
-    esac
-  do  :
-  done
-
-  BASE=${1##*/}
-
-  if      [ -z "$PIDF"  ];  then
-    if    [ -f /var/run/$BASE.pid  ]
-    then  PIDF=/var/run/$BASE.pid
-    elif  [ -f /var/run/$BASE      ]
-    then  PIDF=/var/run/$BASE
-    else  PIDS=$( /bin/pidof -o %PPID $BASE )
-    fi
+ if    [ -z "$PIDF" ]; then
+  if   [ -f /var/run/$BASE.pid ]; then PIDF=/var/run/$BASE.pid
+  elif [ -f /var/run/$BASE     ]; then PIDF=/var/run/$BASE
+  else PIDS=$( /bin/pidof -o %PPID $BASE )
   fi
+ fi
 
-  if    [  -n       "$PIDF"  ];  then
-    if    locked    "$PIDF"  "$BASE"
-    then  read  <  $PIDF;  echo     $REPLY
-    else  false
-    fi
-  elif  [  -n  "$PIDS"  ]
-  then  echo   "$PIDS" 
-  else  false
+ if    [  -n  "$PIDF" ]; then
+  if   locked "$PIDF" "$BASE"
+  then read <  $PIDF; echo $REPLY
+  else false
   fi
+ elif [  -n "$PIDS" ]
+ then echo  "$PIDS" 
+ else return 1
+ fi
 }
 
-killproc()  {
-# killproc [-s signal] [-p pidfile] pathname [signal]
-# [-s signal] supported for backward compatibility
+killproc() {
+ local PIDF PID BASE PIDS SIGL
 
-  local  PIDF  PID  BASE  PIDS  SIGL
+ while
+  case $1 in
+   -p) PIDF=$2 ;;
+   -s) SIGL=$2 ;;
+    *) break ;;
+  esac
+ do shift 2
+ done
 
-  while
-    case  $1  in
-      -p)  PIDF="$2";  shift  2  ;;
-      -s)  SIGL="$2";  shift  2  ;;
-       *)  false                 ;;
-    esac
-  do  :
-  done
+ BASE=${1##*/}; [ -n "$2" ] &&
+ SIGL=$2
+ PIDS="$( pidofproc -p "$PIDF" "$1" )"
 
-  BASE=${1##*/}
-
-  if    [  -n  "$PIDF"  ]
-  then  PIDS="$( pidofproc -p $PIDF "$@" )"
-  else  PIDS="$( pidofproc          "$@" )"
+ if    [ -n    "$PIDS" ]; then
+  if   [ -n    "$SIGL" ]
+  then kill -s "$SIGL" $PIDS
+  else kill -s 15      $PIDS; sleep 3
+       kill -s 9       $PIDS
   fi
-
-  if      [  -n      "$PIDS"  ];  then
-    if    [  -n      "$SIGL"  ]
-    then  kill  -s   "$SIGL"   $PIDS
-    else  kill  -s   15        $PIDS;  sleep 3
-          kill  -s   9         $PIDS
-    fi
-    if    [   -n  "$PIDF"  ]  &&
-          [   -f  "$PIDF"  ]
-    then  rm  -f  "$PIDF"
-    fi
-  else
-    false
+  if   [  -n "$PIDF" ] &&
+       [  -f "$PIDF" ]
+  then rm -f "$PIDF"
   fi
+ else return 1
+ fi
 }
 
-start_daemon()  {
-# start_daemon [-b] [-f] [-n nicelevel] [-p pidfile] pathname [args...]
-# -b for start in background
+start_daemon() {
+ local FORC NICE PIDF BASE PIDS BACK
 
-  local  FORC  NICE  PIDF  BASE  PIDS  BACK
+ while
+  case $1 in
+   -f) FORC=on ;;
+   -n) NICE=$2; shift 1 ;;
+   -p) PIDF=$2; shift 1 ;;
+   -b) BACK=on ;;
+    *) break ;;
+  esac
+ do shift 1
+ done
 
-  while
-    case  $1  in
-      -f)  FORC="on";  shift  1  ;;
-      -n)  NICE="$2";  shift  2  ;;
-      -p)  PIDF="$2";  shift  2  ;;
-      -b)  BACK="on";  shift  1  ;;
-       *)  false                 ;;
-    esac
-  do  :
-  done
+ BASE=${1##*/}
+ PIDS="$( pidofproc -p "$PIDF" "$1" )"
 
-  BASE=${1##*/}
-
-  if    [  -n  "$PIDF"  ]
-  then  PIDS="$( pidofproc -p $PIDF "$@" )"
-  else  PIDS="$( pidofproc          "$@" )"
-  fi
-
-  if    [ -z  "$PIDS" ]  ||
-        [ -n  "$FORC" ]
-  then
-    if      [     -z  "$PIDF"   ]  ||
-            [     -z  "$BACK"   ];  then
-      if    [     -n  "$NICE"   ]
-      then  nice  -n  "$NICE"  "$@"
-      else                     "$@"
-      fi
-    else (
-      if    [     -n  "$NICE"   ]
-      then  nice  -n  "$NICE"  "$@" &
-      else                     "$@" &
-      fi
-      sleep 0.1;  echo  $!  >  $PIDF
-      ) &
-    fi
-  else
-    false
-  fi
+ if   [ -z "$PIDS" ] ||
+      [ -n "$FORC" ]
+ then
+   if     [    -z "$PIDF" ] ||
+          [    -z "$BACK" ]; then
+     if   [    -n "$NICE" ]
+     then nice -n "$NICE" "$@"
+     else "$@"
+     fi
+   else (
+     if   [    -n "$NICE" ]
+     then nice -n "$NICE" "$@" &
+     else "$@" &
+     fi
+     sleep 1; echo $! > $PIDF
+     ) &
+   fi
+ else false
+ fi
 }
 
 
-status()  {
-# status  [-p pidfile] [-l lockfile] pathname
+# Functions below are not specified in LSB 3.1
+# $SERV $NAME must be set
+# $PIDF $LOCK are optional.
+# $OPTS is optional except when mounting
 
-# status function not specified in LSB 3.1
-# however return codes for a status request are specified.
+status() {
+ PIDS="$( pidofproc -p "$PIDF" "$SERV" )"
+ if   [ -n "$PIDS" ]; then log_warning_msg "$NAME is running"; return 0
+ elif [ -f "$PIDF" ]; then log_warning_msg "$NAME is dead and $PIDF exists"; return 1
+ elif [ -n "$LOCK" ] &&
+      [ -f "$LOCK" ]; then log_warning_msg "$NAME is dead and $LOCK exists"; return 2
+                      else log_warning_msg "$NAME is not running"; return 3
+ fi
+}
 
-  local  LOCK  NAME  PIDF  PIDS
+stop() {
+ if   log_warning_msg "$NAME stopping"; killproc -p "$PIDF" -s 15 "$SERV"
+ then log_success_msg "$NAME stopped"
+ else log_failure_msg "$NAME not stopped"; status
+ fi
+}
 
-  while
-    case  $1  in
-      -p)  PIDF="$2";  shift  2  ;;
-      -l)  LOCK="$2";  shift  2  ;;
-       *)  false                 ;;
-    esac
-  do  :
-  done
+start() {
 
-  if    [  -n  "$PIDF"  ]
-  then  PIDS="$( pidofproc -p $PIDF "$@" )"
-  else  PIDS="$( pidofproc          "$@" )"
+ starts() {
+  if   log_warning_msg "$NAME starting"; start_daemon -p "$PIDF" "$SERV" $OPTS
+  then log_success_msg "$NAME started"
+  else log_failure_msg "$NAME not started"; status
   fi
+ }
 
-  if                              [  -n  "$PIDS"  ];  then  return  0
-  elif  [  -n  "$PIDF"  ]  &&  !  [  -f  "$PIDF"  ];  then  return  1
-  elif  [  -n  "$LOCK"  ]  &&     [  -f  "$LOCK"  ];  then  return  2
-                                                      else  return  3
+ startm() {
+  run() {
+   if   !   [ -d "$NAME" ]
+   then mkdir -p "$NAME"; fi &&
+   mount $OPTS   "$NAME"
+  }
+
+  if    ! sed 's/#.*//' /etc/fstab |
+          grep -qw      "$NAME" &&
+        ! grep -qws     "$NAME" /proc/mounts; then
+   if   log_warning_msg "$NAME mounting"; run
+   then log_success_msg "$NAME mounted"
+   else log_failure_msg "$NAME not mounted"
+   fi
   fi
+ }
+
+ case $SERV in
+  mount) startm ;;
+      *) starts ;;
+ esac
+}
+
+    restart() { stop   && sleep 1; start; }
+try_restart() { status && restart; return 0; }
+
+help() { echo "Usage: $0 {start|stop|status|restart}"; }
+
+parse() {
+ case "$1" in
+        start)       start ;;
+      restart)     restart ;;
+  try-restart) try_restart ;;
+    stop) stop   ;;
+  status) status ;;
+  *) help ;;
+ esac
 }
diff --git a/trunk/grimoire/initramfs.d/init.d.on/initramfs b/trunk/grimoire/initramfs.d/init.d.on/initramfs
--- a/trunk/grimoire/initramfs.d/init.d.on/initramfs
+++ b/trunk/grimoire/initramfs.d/init.d.on/initramfs
@@ -15,219 +15,227 @@
 
 . /lib/lsb/init-functions
 
-NAME="initramfs"
+NAME=initramfs
 
-update_lilo()  {
-  local  T="	"
+update_lilo() {
+ local T="	"
 
-  lm()  {
-    grep  -q     large-memory   $1  ||
-    sed   -i  '1ilarge-memory'  $1
-  }
+ lm() {
+  grep -q    large-memory  $1 ||
+  sed  -i '1ilarge-memory' $1
+ }
 
-  lm  /etc/lilo.conf.head
-  lm  /etc/lilo.conf
+ lm /etc/lilo.conf.head
+ lm /etc/lilo.conf
 
-  grep   -l  /boot/initrf.gz  /etc/lilo.conf  /etc/lilo.conf.head  |
-  xargs  -r  --max-lines=2  sed  -i  '\,/boot/initrf.gz,d'
+ grep  -l /boot/initrf.gz /etc/lilo.conf /etc/lilo.conf.head |
+ xargs -r --max-lines=2 sed -i '\,/boot/initrf.gz,d'
 
-  find  /boot  -maxdepth 2  -mindepth 2  \
-               -type f      -name linux  \
-               -printf      '%h/initrf.gz\t%h/linux\n'  |
-  while  read   IRF  IMG;  do
-    grep  -q  "$IRF"                                     /etc/lilo.conf  ||
-    sed   -i     "s:$IMG$:$IMG\n${T}initrd$T$T=$T$IRF:"  /etc/lilo.conf
-  done
+ find /boot -maxdepth 2 -mindepth 2  \
+            -type f     -name linux  \
+            -printf     '%h/initrf.gz\t%h/linux\n' |
+ while read  IRF  IMG; do
+  grep -q  "$IRF"                                    /etc/lilo.conf  ||
+  sed  -i     "s:$IMG$:$IMG\n${T}initrd$T$T=$T$IRF:" /etc/lilo.conf
+ done
 }
 
 
-run_lilo()  {
-  sync
-  /sbin/lilo  -P ignore
+run_lilo() {
+ sync
+ /sbin/lilo -P ignore
 }
 
 
-mkinitrf()  {
+mkinitrf() {
 
-  gcpio()  {
-    local  INC="\,/lib/modules/$1$,p
-                \,/lib/modules/$1/,p"
-    local  OUT='\,^/lib/modules/,d'
-    local  OLD="/boot/$1/initrf.gz"
-    local  NEW="/tmp/initrf.gz.$RANDOM$$$RANDOM.new"
+ gcpio() {
+  local INC="\,/lib/modules/$1$,p
+             \,/lib/modules/$1/,p"
+  local OUT='\,^/lib/modules/,d'
+  local OLD="/boot/$1/initrf.gz"
+  local NEW="/tmp/initrf.gz.$RANDOM$$$RANDOM.new"
 
-    echo  -n  > $NEW
-    chmod 0600  $NEW
+  echo -n  > $NEW
+  chmod 0600 $NEW
 
-    sed    "$INC;$OUT"  |
-    if    !  cpio  -o  -H newc  --quiet;  then  rm  -f  $NEW;  return 1;  fi  |
-    if    !  gzip  -1  >  $NEW;           then  rm  -f  $NEW;  return 1;  fi
-    if    !  [     -s     $NEW  ];        then  rm  -f  $NEW;  return 1;  fi
+  sed "$INC;$OUT"  |
+  if  ! cpio -o -H newc --quiet; then rm -f $NEW; return 1; fi |
+  if  ! gzip -1 > $NEW;          then rm -f $NEW; return 1; fi
+  if  ! [    -s   $NEW ];        then rm -f $NEW; return 1; fi
 
-    rm  -f    $OLD
-    mv  $NEW  $OLD
-  }
+  rm -f   $OLD
+  mv $NEW $OLD
+ }
 
-  echo  "$EVERY"  |  gcpio   "$1"
+ echo "$EVERY" | gcpio "$1"
 }
 
 
 
 every()  {
-  local  KBD  KEYMAPS  LIB64
+ local KBD KEYMAPS LIB64
 
-  exists()  {
-    while  read
-    do     [[  -e  $REPLY  ]]  &&
-           echo   "$REPLY"
-    done
-  }
-
-  if    [  -d   /usr/share/kbd/keymaps  ]
-  then  KEYMAPS=/usr/share/kbd/keymaps
-         KBD='1i/usr/share/kbd
-              1i/usr/share/kbd/keymaps'
-  fi
-
-  if    [  -d  /lib64  ]
-  then   LIB64=/lib64
-  fi
-
-  find  /bin /dev /etc /lib $LIB64 /sbin $KEYMAPS  |
-  sed   "\,^/dev/pts/,d
-         \,^/dev/.udev,d
-         \,^/dev/shm/,d
-         \,^/etc/sorcery/,d
-         \,^/etc/asciidoc/,d
-         \,^/etc/avahi/,d
-         \,^/etc/chipcard/,d
-         \,^/etc/chipcard3/,d
-         \,^/etc/courier/,d
-         \,^/etc/cups/,d
-         \,^/etc/elvis.default/stubs/,d
-         \,^/etc/fonts/,d
-         \,^/etc/gconf/,d
-         \,^/etc/gdm/,d
-         \,^/etc/gtk/,d
-         \,^/etc/httpd/,d
-         \,^/etc/kde\.,d
-         \,^/etc/mono/,d
-         \,^/etc/mplayer/,d
-         \,^/etc/mtab/,d
-         \,^/etc/openldap/,d
-         \,^/etc/ppp/,d
-         \,^/etc/sane.d/,d
-         \,^/etc/sound/,d
-         \,^/etc/squid/,d
-         \,^/etc/ssh/,d
-         \,^/etc/ssl/,d
-         \,^/etc/xdg/,d
-         \,^/etc/bootblaze.conf,d
-         \,^/etc/protocols.old$,d
-         \,^/etc/services.old$,d
-         \,^/etc/xml,d
-         \,^/lib.*\.la$,d
-         \,^/lib.*lib.*\.a$,d
-         \,^/sbin/dmsetup\.static$,d
-         \,^/sbin/insmod\.static$,d
-         \,^/sbin/sln$,d
-         1i/init
-         1i/media
-         1i/media/root
-         1i/proc
-         1i/sys
-         1i/usr
-         1i/usr/share
-         $KBD
-         1i/usr/share/terminfo
-         1i/usr/share/terminfo/l
-         1i/usr/share/terminfo/l/linux"  |  exists
-}
-
-
-initrf_update()  {
-  if    [   -f  /boot/initrf.gz  ]
-  then  rm  -f  /boot/initrf.gz
-  fi
-
-  [      -d       /media/root  ]  ||
-  mkdir  -pm 0755 /media/root
-
-  local  EVERY="$(  every  )"
-
-  update_lilo
-
-  find  /boot  -maxdepth 2  -mindepth 2  \
-               -type f      -name linux  \
-               -printf      '%h\n'       |
-  cut  -d /  -f3                         |
-  while  read       VERSION
-  do     mkinitrf  $VERSION
-  done
-
-  run_lilo
-}
-
-
-initrf_present()  {
-  find  /boot  -maxdepth 2  -mindepth 2  \
-               -type f      -name linux  \
-               -printf      '%h\n'       |
-  while  read
-  do     [  -f  "$REPLY/initrf.gz"  ]    ||  return 1
+ exists()  {
+  while read
+  do    [[ -e $REPLY ]] &&
+        echo "$REPLY"
   done
 }
 
+ if   [  -d   /usr/share/kbd/keymaps  ]
+ then KEYMAPS=/usr/share/kbd/keymaps
+       KBD='1i/usr/share/kbd
+            1i/usr/share/kbd/keymaps'
+ fi
 
-initrf_current()  {
-  local  DIRS='/bin /etc/bash.d /etc/init.d /etc/lvm /etc/modules.d'
-         DIRS+=' /etc/udev /lib /sbin'
+ if   [  -d  /lib64  ]
+ then  LIB64=/lib64
+ fi
+
+ find /bin /dev /etc /lib $LIB64 /sbin $KEYMAPS |
+ sed "\
+\,^/dev/pts/,d
+\,^/dev/.udev,d
+\,^/dev/shm/,d
+\,^/etc/sorcery/,d
+\,^/etc/asciidoc/,d
+\,^/etc/avahi/,d
+\,^/etc/chipcard/,d
+\,^/etc/chipcard3/,d
+\,^/etc/courier/,d
+\,^/etc/cups/,d
+\,^/etc/elvis.default/stubs/,d
+\,^/etc/fonts/,d
+\,^/etc/gconf/,d
+\,^/etc/gdm/,d
+\,^/etc/gtk/,d
+\,^/etc/httpd/,d
+\,^/etc/kde\.,d
+\,^/etc/mono/,d
+\,^/etc/mplayer/,d
+\,^/etc/mtab/,d
+\,^/etc/openldap/,d
+\,^/etc/ppp/,d
+\,^/etc/sane.d/,d
+\,^/etc/sound/,d
+\,^/etc/squid/,d
+\,^/etc/ssh/,d
+\,^/etc/ssl/,d
+\,^/etc/xdg/,d
+\,^/etc/bootblaze.conf,d
+\,^/etc/protocols.old$,d
+\,^/etc/services.old$,d
+\,^/etc/xml,d
+\,^/lib.*\.la$,d
+\,^/lib.*lib.*\.a$,d
+\,^/sbin/dmsetup\.static$,d
+\,^/sbin/insmod\.static$,d
+\,^/sbin/sln$,d
+1i/init
+1i/media
+1i/media/root
+1i/proc
+1i/sys
+1i/usr
+1i/usr/share
+$KBD
+1i/usr/share/terminfo
+1i/usr/share/terminfo/l
+1i/usr/share/terminfo/l/linux" | exists
+}
+
+
+initrf_update() {
+ if   [  -f /boot/initrf.gz ]
+ then rm -f /boot/initrf.gz
+ fi
+
+ [     -d       /media/root ] ||
+ mkdir -pm 0755 /media/root
+
+ local EVERY="$( every )"
+
+ update_lilo
+
+ find /boot -maxdepth 2 -mindepth 2 \
+            -type f     -name linux \
+            -printf     '%h\n'      |
+ cut -d / -f3                       |
+ while  read      VERSION
+ do     mkinitrf $VERSION
+ done
+
+ run_lilo
+}
+
+
+initrf_present() {
+ find /boot -maxdepth 2 -mindepth 2 \
+            -type f     -name linux \
+            -printf     '%h\n'      |
+ while read
+ do    [ -f "$REPLY/initrf.gz" ] || return 1
+ done
+}
+
+
+initrf_current() {
+ local DIRS='/bin /etc/bash.d /etc/init.d /etc/lvm /etc/modules.d'
+       DIRS+=' /etc/udev /lib /sbin'
  
-  [  -d          /lib64  ]  &&
-         DIRS+=' /lib64'
+ [ -d          /lib64 ] &&
+       DIRS+=' /lib64'
 
-  local  FILES='/etc/fstab /etc/hostname /etc/inittab'
-         FILES+=' /etc/lilo.conf /etc/lilo.conf.head'
-         FILES+=' /etc/modprobe.conf /etc/passwd /etc/shadow'
+ local FILES='/etc/fstab /etc/hostname /etc/inittab'
+       FILES+=' /etc/lilo.conf /etc/lilo.conf.head'
+       FILES+=' /etc/modprobe.conf /etc/passwd /etc/shadow'
 
-  local  OMIT='\,/etc/init.d/log,d'
+ local OMIT='\,/etc/init.d/log,d'
 
-  find  /boot  -mindepth  2  -mindepth 2      \
-               -type f       -name initrf.gz  \
-               -printf '%T@	%p\n'         |
-  LC_ALL=C  sort  -g    |
-  while     read  JUNK  REPLY;  do
-    find  $DIRS  $FILES  -type f  -newer  $REPLY  |
-    sed  "$OMIT"  |  grep  -q  .  &&
-    return  1    ||
-    return
-  done
+ find /boot -mindepth  2 -mindepth 2      \
+            -type f      -name initrf.gz  \
+            -printf '%T@	%p\n'     |
+ LC_ALL=C sort -g |
+ while    read  JUNK  REPLY;  do
+  find $DIRS $FILES -type f -newer $REPLY |
+  sed "$OMIT" | grep -q . &&
+  return 1 ||
+  return
+ done
 }
 
 
-on_cd()  {
-    if  !  [   -d  /boot/isolinux  ];  then  return  1
-  elif  !  touch   /tmp/writeable   ;  then  return
-  else  rm     -f  /tmp/writeable   ;        return  1
-    fi  2>/dev/null
+on_cd() {
+   if ! [   -d /boot/isolinux ]; then return 1
+ elif ! touch  /tmp/writeable  ; then return
+ else rm    -f /tmp/writeable  ;      return 1
+   fi 2>/dev/null
 }
 
 
-begin()  {
-  if    on_cd
-  then  return
-  elif  initrf_present  &&
-        initrf_current
-  then  return
-  elif  log_warning_msg  "$NAME updating";  initrf_update
-  then  log_success_msg  "$NAME updated"
-  else  log_failure_msg  "$NAME failed"
-        if    [  "$1"  ==  stop  ]
-        then  sulogin  -t 300  &>/dev/console  0</dev/console
-        fi
-  fi
+begin() {
+ if   on_cd
+ then return
+ elif initrf_present &&
+      initrf_current
+ then return
+ elif log_warning_msg "$NAME updating";  initrf_update
+ then log_success_msg "$NAME updated"
+ else log_failure_msg "$NAME failed"
+      if   [ "$1" == stop ]
+      then sulogin -t 300 &>/dev/console 0</dev/console
+      fi
+ fi
 }
 
 
-log_warning_msg  "$NAME checking";  begin  "$1"
-log_success_msg  "$NAME checked"
+main() {
+ log_warning_msg "$NAME checking"; begin "$1"
+ log_success_msg "$NAME checked"
+}
+
+case $1 in
+ stop) main stop ;;
+    *) main ;;
+esac
