improvements

diff --git a/trunk/grimoire/gtk+.d/init.d.on/gtk-update-icon-cache b/trunk/grimoire/gtk+.d/init.d.on/gtk-update-icon-cache
--- a/trunk/grimoire/gtk+.d/init.d.on/gtk-update-icon-cache
+++ b/trunk/grimoire/gtk+.d/init.d.on/gtk-update-icon-cache
@@ -11,23 +11,25 @@
 
 . /lib/lsb/init-functions
 
-IC=icon-theme.cache
+stop(){
+ IC=icon-theme.cache
 
-find /usr/share/icons -mindepth 2 -maxdepth 2 \
-     -name index.theme -printf '%h\n' |
-while read REPLY; do
- log_warning_msg "$IC in $REPLY checking"
- if ! [ -f $REPLY/$IC ] ||
-    find   $REPLY -type f -newer \
-           $REPLY/$IC | grep -q .
- then log_warning_msg "$IC in $REPLY not current"; echo "$REPLY"
- else log_warning_msg "$IC in $REPLY current"
- fi
-done |
-while read REPLY; do
- if   log_warning_msg "$IC in $REPLY Updating"; 
-      gtk-update-icon-cache -f $REPLY
- then log_success_msg "$IC in $REPLY Updated"
- else log_failure_msg "$IC in $REPLY Update failed"
- fi
-done
+ find /usr/share/icons -mindepth 2 -maxdepth 2 \
+      -name index.theme -printf '%h\n' |
+ while read REPLY; do
+  log_warning_msg "$IC in $REPLY checking"
+  if ! [ -f $REPLY/$IC ] ||
+     find   $REPLY -type f -newer \
+            $REPLY/$IC | grep -q .
+  then log_warning_msg "$IC in $REPLY not current"; echo "$REPLY"
+  else log_warning_msg "$IC in $REPLY current"
+  fi
+ done |
+ while read REPLY; do
+  if   log_warning_msg "$IC in $REPLY Updating"; 
+       gtk-update-icon-cache -f $REPLY
+  then log_success_msg "$IC in $REPLY Updated"
+  else log_failure_msg "$IC in $REPLY Update failed"
+  fi
+ done
+}
diff --git a/trunk/grimoire/init-scripts.d/init.d.on/cgroup-init b/trunk/grimoire/init-scripts.d/init.d.on/cgroup-init
--- a/trunk/grimoire/init-scripts.d/init.d.on/cgroup-init
+++ b/trunk/grimoire/init-scripts.d/init.d.on/cgroup-init
@@ -11,28 +11,30 @@
 # Short-Description: joins init to a cgroup
 ### END INIT INFO
 
-[ $1 == start ] || exit 0
+[ $1 == start ] || exit 5
 
 . /lib/lsb/init-functions
 
-find_cgroup(){
- local JUNK DIR TYPE
- while read JUNK DIR TYPE JUNK; do
-  if [ "$TYPE" == cgroup ] && [ -f $DIR/tasks ]; then
-   CG=$DIR
-   return 0
-  fi
- done < /proc/mounts
- return 1
-}
+start(){
+ find_cgroup(){
+  local JUNK DIR TYPE
+  while read JUNK DIR TYPE JUNK; do
+   if [ "$TYPE" == cgroup ] && [ -f $DIR/tasks ]; then
+    CG=$DIR
+    return 0
+   fi
+  done < /proc/mounts
+  return 1
+ }
 
-join(){
- find_cgroup &&
- mkdir -p $CG/daemon/init &&
- echo 1 > $CG/daemon/init/tasks
-}
+ join(){
+  find_cgroup &&
+  mkdir -p $CG/daemon/init &&
+  echo 1 > $CG/daemon/init/tasks
+ }
 
-if   log_warning_msg "init joining cgroup"; join
-then log_success_msg "init joined  cgroup"
-else log_failure_msg "init failed to join cgroup"
-fi
+ if   log_warning_msg "init joining cgroup"; join
+ then log_success_msg "init joined  cgroup"
+ else log_failure_msg "init failed to join cgroup"
+ fi
+}
diff --git a/trunk/grimoire/init-scripts.d/init.d.on/events b/trunk/grimoire/init-scripts.d/init.d.on/events
--- a/trunk/grimoire/init-scripts.d/init.d.on/events
+++ b/trunk/grimoire/init-scripts.d/init.d.on/events
@@ -7,13 +7,15 @@
 # Short-Description: eliminates slugish keyboard pointer event handling during high load
 ### END INIT INFO
 
-if [ "$1" == try-restart ]; then exit; fi
+if [ "$1" == try-restart ]; then exit 5; fi
 
 . /lib/lsb/init-functions
 
-pgrep -u root events/0  | grep -q . &&
-if   log_warning_msg "renice -19 \$( pgrep -u root events/0 ) executing"
-                      renice -19  $( pgrep -u root events/0 ) &>/dev/null
-then log_success_msg "renice -19 \$( pgrep -u root events/0 ) executed"
-else log_failure_msg "renice -19 \$( pgrep -u root events/0 ) failed"
-fi
+start(){
+ pgrep -u root events/0  | grep -q . &&
+ if   log_warning_msg "renice -19 \$( pgrep -u root events/0 ) executing"
+                       renice -19  $( pgrep -u root events/0 ) &>/dev/null
+ then log_success_msg "renice -19 \$( pgrep -u root events/0 ) executed"
+ else log_failure_msg "renice -19 \$( pgrep -u root events/0 ) failed"
+ fi
+}
diff --git a/trunk/grimoire/nagios.d/init.d/nagios b/trunk/grimoire/nagios.d/init.d/nagios
--- a/trunk/grimoire/nagios.d/init.d/nagios
+++ b/trunk/grimoire/nagios.d/init.d/nagios
@@ -13,47 +13,34 @@
 
 . /lib/lsb/init-functions
 
-PIDF=/var/run/nagios.pid
-SERV=/usr/sbin/nagios
-NAME=nagios
-CONF=/etc/nagios/nagios.cfg
+pid_file /var/run/nagios.pid
+server /usr/sbin/nagios
+name nagios
+config /etc/nagios/nagios.cfg
 
-start()  {
-  log_warning_msg  "$NAME starting"
-  if  $SERV -v $CONF;  then
-    touch                 /var/nagios/{nagios.log,retention.dat}  $PIDF  /var/lock/subsys/nagios
-    chown  nagios:nagios  /var/nagios/{nagios.log,retention.dat}  $PIDF
-    rm     -f             /var/nagios/rw/nagios.cmd
-    if    start_daemon     -p $PIDF $SERV -d $CONF
-    then  log_success_msg  "$NAME started"
-    else  log_failure_msg  "$NAME not started"
-          status
-    fi
-  else
-    log_failure_msg  "$NAME not started - configuration file error"
-    status
+start(){
+ log_warning_msg  "$NAME starting"
+ if  $SERV -v $CONF; then
+  touch               /var/nagios/{nagios.log,retention.dat} $PIDF /var/lock/subsys/nagios
+  chown nagios:nagios /var/nagios/{nagios.log,retention.dat} $PIDF
+  rm    -f            /var/nagios/rw/nagios.cmd
+  if   start_daemon    -p $PIDF $SERV -d $CONF
+  then log_success_msg "$NAME started"
+  else log_failure_msg "$NAME not started"
+       status
   fi
+ else
+  log_failure_msg  "$NAME not started - configuration file error"
+  status
+ fi
 }
 
-reload()  {
-  PIDS="$( pidofproc -p $PIDF $SERV )"
-  if    [ -n            "$PIDS" ]
-  then  kill  -s SIGHUP  $PIDS  &&
-        log_success_msg "$NAME configuration reloaded"
-  fi
+reload(){
+ PIDS="$( pidofproc -p $PIDF $SERV )"
+ if   [ -n            "$PIDS" ]
+ then kill -s SIGHUP   $PIDS  &&
+      log_success_msg "$NAME configuration reloaded"
+ fi
 }
 
-help()  {
-  echo "Usage: $0 {restart|try-restart|reload|force-reload|start|status|stop}" 1>&2
-}
-
-case  $1  in
-       restart)      restart  ;;
-   try-restart)  try_restart  ;;
-        reload)  try_restart  ;;
-  force-reload)  try_restart  ;;
-         start)  start        ;;
-        status)  status       ;;
-          stop)  stop         ;;
-             *)  help         ;;
-esac
+help(){ echo "Usage: $0 {restart|try-restart|reload|force-reload|start|status|stop}" 1>&2; }
diff --git a/trunk/grimoire/oss.d/init.d.on/ossdetect b/trunk/grimoire/oss.d/init.d.on/ossdetect
--- a/trunk/grimoire/oss.d/init.d.on/ossdetect
+++ b/trunk/grimoire/oss.d/init.d.on/ossdetect
@@ -1,29 +1,26 @@
 #!/bin/bash
 
 ### BEGIN INIT INFO
-# Default-Mode: 510
+# Default-Mode: 500
 # Required-Start: $local_fs
 # Default-Start: 1 2 3 4 5
 # Short-Description: ossdetect detects soundcards and writes coinfig to  /etc/oss/installed_drivers
 ### END INIT INFO
 
+if [ "$1" == try-restart ]; then exit 5; fi
+if [ -f /etc/oss/installed_drivers ]; then exit 0; fi
+
 . /lib/lsb/init-functions
 
-NAME=ossdetect
-SERV=/usr/sbin/ossdetect
-OPTS=-i
+name ossdetect
+server /usr/sbin/ossdetect
+options -i
 
 start(){
- if ! [ -f /etc/oss/installed_drivers ]
- then
-  log_warning_msg "About to run $SERV to detect audio devices."
-  if   $SERV $OPTS
-  then log_success_msg "$SERV exited successfully"
-  else log_failure_msg "$SERV exited with an error"
-  fi
+ if   log_warning_msg "About to run $SERV to detect audio devices."; $SERV $OPTS
+ then log_success_msg "$SERV exited successfully"
+ else log_failure_msg "$SERV exited with an error"
  fi
 }
-       stop(){ :; }
-    restart(){ start; }
-try_restart(){ start; }
-parse "$@"
+
+stop(){ :; }
diff --git a/trunk/grimoire/suspend-utils.d/init.d.on/resume b/trunk/grimoire/suspend-utils.d/init.d.on/resume
--- a/trunk/grimoire/suspend-utils.d/init.d.on/resume
+++ b/trunk/grimoire/suspend-utils.d/init.d.on/resume
@@ -7,11 +7,13 @@
 # Short-Description: resumes from suspend to RAM or disk.
 ### END INIT INFO
 
-[ "$1" == try-restart ] && exit 0
+[ "$1" == try-restart ] && exit 5
 
 . /lib/lsb/init-functions
 
-if   log_warning_msg "resuming"; echo | /sbin/resume
-then log_success_msg "resumed"
-else log_failure_msg "resume failed"
-fi
+start(){
+ if   log_warning_msg "resuming"; echo | /sbin/resume
+ then log_success_msg "resumed"
+ else log_failure_msg "resume failed"
+ fi
+}
